VehicleList = {
	Cars = {
		SuperMax = 4,
		ClassiqueMax = 4,
		SedansMax = 6,
        SportMax = 6,
        
		MuscleMax = 5,
        VansMax = 5,
        
		SuvMax = 9,
		OffRoadMax = 10,
		CoupeMax = 8,
		CompactsMax = 12,
		MotoMax = 10,
	},
    Classique = {
        {Name = "Ardent", Value = "ardent", Price = math.random(0, 0)},
        {Name = "BType", Value = "btype", Price = math.random(0, 0)},
        {Name = "Casco", Value = "casco", Price = math.random(0, 0)},
        {Name = "Cheetah", Value = "cheetah2", Price = math.random(0, 0)},
        {Name = "Coquette", Value = "coquette2", Price = math.random(0, 0)},
        {Name = "Dynasty", Value = "dynasty", Price = math.random(0, 0)},
        {Name = "Fagoloa", Value = "fagaloa", Price = math.random(0, 0)},
        {Name = "GT500", Value = "gt500", Price = math.random(0, 0)},
        {Name = "Infernus", Value = "infernus2", Price = math.random(0, 0)},
        {Name = "Jb700", Value = "jb700", Price = math.random(0, 0)},
        {Name = "Mamba", Value = "mamba", Price = math.random(0, 0)},
        {Name = "Manana", Value = "manana", Price = math.random(0, 0)},
        {Name = "Michelli", Value = "michelli", Price = math.random(0, 0)},
        {Name = "Monroe", Value = "monroe", Price = math.random(0, 0)},
        {Name = "Nebula", Value = "nebula", Price = math.random(0, 0)},
        {Name = "Peyote", Value = "peyote", Price = math.random(0, 0)},
        {Name = "Pigalle", Value = "pigalle", Price = math.random(0, 0)},
        {Name = "RapidGT", Value = "rapidgt3", Price = math.random(0, 0)},
        {Name = "Retinue", Value = "retinue", Price = math.random(0, 0)},
        {Name = "Savestra", Value = "savestra", Price = math.random(0, 0)},
        {Name = "Stringer", Value = "stinger", Price = math.random(0, 0)},
        {Name = "StringerGT", Value = "stingergt", Price = math.random(0, 0)},
        {Name = "Stromberg", Value = "stromberg", Price = math.random(0, 0)},
        {Name = "Swiner", Value = "swinger", Price = math.random(0, 0)},
        {Name = "Torero", Value = "torero", Price = math.random(0, 0)},
        {Name = "Tornado", Value = "tornado2", Price = math.random(0, 0)},
        {Name = "Turismo", Value = "turismo2", Price = math.random(0, 0)},
        {Name = "Viseris", Value = "viseris", Price = math.random(0, 0)},
        {Name = "Z190", Value = "z190", Price = math.random(0, 0)},
        {Name = "Ztype", Value = "ztype", Price = math.random(0, 0)},
        {Name = "Zion", Value = "zion3", Price = math.random(0, 0)},
        {Name = "Cheburek", Value = "cheburek", Price = math.random(0, 0)},
    }, 
    Super = {
        {Name = "Adder", Value = "adder", Price = math.random(0, 0)},
        {Name = "Autrach", Value = "autarch", Price = math.random(0, 0)},
        {Name = "Banshee", Value = "banshee2", Price = math.random(0, 0)},
        {Name = "Bullet", Value = "bullet", Price = math.random(0, 0)},
        {Name = "Cheetah", Value = "cheetah", Price = math.random(0, 0)},
        {Name = "Cyclone", Value = "cyclone", Price = math.random(0, 0)},
        {Name = "Entity", Value = "entity2", Price = math.random(0, 0)},
        {Name = "EntityXF", Value = "entityxf", Price = math.random(0, 0)},
        {Name = "Emerus", Value = "emerus", Price = math.random(0, 0)},
        {Name = "Fmj", Value = "fmj", Price = math.random(0, 0)},
        {Name = "Furia", Value = "furia", Price = math.random(0, 0)},
        {Name = "Gp1", Value = "gp1", Price = math.random(0, 0)},
        {Name = "Infernus", Value = "infernus", Price = math.random(0, 0)},
        {Name = "ItaliGTB", Value = "italigtb", Price = math.random(0, 0)},
        {Name = "Krieger", Value = "krieger", Price = math.random(0, 0)},
        {Name = "Le7b", Value = "le7b", Price = math.random(0, 0)},
        {Name = "Nero", Value = "nero", Price = math.random(0, 0)},
        {Name = "Osiris", Value = "osiris", Price = math.random(0, 0)},
        {Name = "Penetrator", Value = "penetrator", Price = math.random(0, 0)},
        {Name = "Pfister811", Value = "pfister811", Price = math.random(0, 0)},
        {Name = "Reaper", Value = "reaper", Price = math.random(0, 0)},
        {Name = "Sc1", Value = "sc1", Price = math.random(0, 0)},
        {Name = "Sheava", Value = "sheava", Price = math.random(0, 0)},
        {Name = "SultanRS", Value = "sultanrs", Price = math.random(0, 0)},
        {Name = "T20", Value = "t20", Price = math.random(0, 0)},
        {Name = "Taipan", Value = "taipan", Price = math.random(0, 0)},
        {Name = "Tempesta", Value = "tempesta", Price = math.random(0, 0)},
        {Name = "Tezeract", Value = "tezeract", Price = math.random(0, 0)},
        {Name = "Thrax", Value = "thrax", Price = math.random(0, 0)},
        {Name = "Tigon", Value = "tigon", Price = math.random(0, 0)},
        {Name = "TurismoR", Value = "turismor", Price = math.random(0, 0)},
        {Name = "Tyrant", Value = "tyrant", Price = math.random(0, 0)},
        {Name = "Tyrus", Value = "tyrus", Price = math.random(0, 0)},
        {Name = "Vacca", Value = "vacca", Price = math.random(0, 0)},
        {Name = "Vagner", Value = "vagner", Price = math.random(0, 0)},
        {Name = "Visione", Value = "visione", Price = math.random(0, 0)},
        {Name = "Voltic", Value = "voltic", Price = math.random(0, 0)},
        {Name = "Xa21", Value = "xa21", Price = math.random(0, 0)},
        {Name = "Zentorno", Value = "zentorno", Price = math.random(0, 0)},
        {Name = "Zorusso", Value = "zorrusso", Price = math.random(0, 0)},
    },
    Sedans = {
        {Name = "Asea", Value = "asea", Price = math.random(0, 0)},
        {Name = "Asterope", Value = "asterope", Price = math.random(0, 0)},
        {Name = "Cog55", Value = "cog55", Price = math.random(0, 0)},
        {Name = "Cognoscenti", Value = "cognoscenti", Price = math.random(0, 0)},
        {Name = "Emperor", Value = "emperor", Price = math.random(0, 0)},
        {Name = "Fugitive", Value = "fugitive", Price = math.random(0, 0)},
        {Name = "Glendale", Value = "glendale", Price = math.random(0, 0)},
        {Name = "Ingot", Value = "ingot", Price = math.random(0, 0)},
        {Name = "Intruder", Value = "intruder", Price = math.random(0, 0)},
        {Name = "Limo", Value = "limo2", Price = math.random(0, 0)},
        {Name = "Premier", Value = "premier", Price = math.random(0, 0)},
        {Name = "Primo", Value = "primo", Price = math.random(0, 0)},
        {Name = "Regina", Value = "regina", Price = math.random(0, 0)},
        {Name = "Romero", Value = "romero", Price = math.random(0, 0)},
        {Name = "Stafford", Value = "stafford", Price = math.random(0, 0)},
        {Name = "Stanier", Value = "stanier", Price = math.random(0, 0)},
        {Name = "Stratum", Value = "stratum", Price = math.random(0, 0)},
        {Name = "SuperD", Value = "superd", Price = math.random(0, 0)},
        {Name = "Surge", Value = "surge", Price = math.random(0, 0)},
        {Name = "Tailgater", Value = "tailgater", Price = math.random(0, 0)},
        {Name = "Warrener", Value = "warrener", Price = math.random(0, 0)},
        {Name = "Washington", Value = "washington", Price = math.random(0, 0)},
    }, 
    Sport = {
        {Name = "Alpha", Value = "alpha", Price = math.random(0, 0)},
        {Name = "Banshee", Value = "banshee", Price = math.random(0, 0)},
        {Name = "BestiaGTS", Value = "bestiagts", Price = math.random(0, 0)},
        {Name = "Blista", Value = "blista2", Price = math.random(0, 0)},
        {Name = "Buffalo", Value = "buffalo", Price = math.random(0, 0)},
        {Name = "Carbonizzare", Value = "carbonizzare", Price = math.random(0, 0)},
        {Name = "Comet", Value = "comet2", Price = math.random(0, 0)},
        {Name = "Coquette", Value = "coquette", Price = math.random(0, 0)},
        {Name = "Drafter", Value = "drafter", Price = math.random(0, 0)},
        {Name = "Deveste", Value = "deveste", Price = math.random(0, 0)},
        {Name = "Elegy", Value = "elegy", Price = math.random(0, 0)},
        {Name = "ElegyRS", Value = "elegy2", Price = math.random(0, 0)},
        {Name = "Feltzer", Value = "feltzer2", Price = math.random(0, 0)},
        {Name = "FlashGT", Value = "flashgt", Price = math.random(0, 0)},
        {Name = "FuroreGT", Value = "furoregt", Price = math.random(0, 0)},
        {Name = "Fusilade", Value = "fusilade", Price = math.random(0, 0)},
        {Name = "Futo", Value = "futo", Price = math.random(0, 0)},
        {Name = "GB200", Value = "gb200", Price = math.random(0, 0)},
        {Name = "Hotring", Value = "hotring", Price = math.random(0, 0)},
        {Name = "Komoda", Value = "komoda", Price = math.random(0, 0)},
        {Name = "Imorgon", Value = "imorgon", Price = math.random(0, 0)},
        {Name = "Issi", Value = "issi7", Price = math.random(0, 0)},
        {Name = "ItaliGTO", Value = "italigto", Price = math.random(0, 0)},
        {Name = "Jugular", Value = "jugular", Price = math.random(0, 0)},
        {Name = "Jester", Value = "jester", Price = math.random(0, 0)},
        {Name = "Khamelion", Value = "khamelion", Price = math.random(0, 0)},
        {Name = "Kuruma", Value = "kuruma", Price = math.random(0, 0)},
        {Name = "Locust", Value = "locust", Price = math.random(0, 0)},
        {Name = "Lynx", Value = "lynx", Price = math.random(0, 0)},
        {Name = "Massacro", Value = "massacro", Price = math.random(0, 0)},
        {Name = "Neo", Value = "neo", Price = math.random(0, 0)},
        {Name = "Neon", Value = "neon", Price = math.random(0, 0)},
        {Name = "NineF", Value = "ninef", Price = math.random(0, 0)},
        {Name = "Omnis", Value = "omnis", Price = math.random(0, 0)},
        {Name = "Paragon", Value = "paragon", Price = math.random(0, 0)},
        {Name = "Pariah", Value = "pariah", Price = math.random(0, 0)},
        {Name = "Penumbra", Value = "penumbra", Price = math.random(0, 0)},
        {Name = "Raiden", Value = "raiden", Price = math.random(0, 0)},
        {Name = "RapidGT", Value = "rapidgt", Price = math.random(0, 0)},
        {Name = "Raptor", Value = "raptor", Price = math.random(0, 0)},
        {Name = "Revolter", Value = "revolter", Price = math.random(0, 0)},
        {Name = "Ruston", Value = "ruston", Price = math.random(0, 0)},
        {Name = "Schafter", Value = "schafter3", Price = math.random(0, 0)},
        {Name = "Schlagen", Value = "schlagen", Price = math.random(0, 0)},
        {Name = "Schwarzer", Value = "schwarzer", Price = math.random(0, 0)},
        {Name = "Sentinel", Value = "sentinel3", Price = math.random(0, 0)},
        {Name = "Seven70", Value = "seven70", Price = math.random(0, 0)},
        {Name = "Specter", Value = "specter", Price = math.random(0, 0)},
        {Name = "Streiter", Value = "streiter", Price = math.random(0, 0)},
        {Name = "Sugoi", Value = "sugoi", Price = math.random(0, 0)},
        {Name = "Sultan", Value = "sultan", Price = math.random(0, 0)},
        {Name = "Surano", Value = "surano", Price = math.random(0, 0)},
        {Name = "Tampa", Value = "tampa2", Price = math.random(0, 0)},
        {Name = "Tropos", Value = "tropos", Price = math.random(0, 0)},
        {Name = "Verlierer", Value = "verlierer2", Price = math.random(0, 0)},
        {Name = "VSTR", Value = "vstr", Price = math.random(0, 0)},
    },
    Muscle = {
        {Name = "Blade", Value = "blade", Price = math.random(0, 0)},
        {Name = "Buccaneer", Value = "buccaneer", Price = math.random(0, 0)},
        {Name = "Buccaneer Cabriolé", Value = "buccaneer2", Price = math.random(0, 0)},
        {Name = "Chino", Value = "chino", Price = math.random(0, 0)},
        {Name = "Chino Cabriolé", Value = "chino2", Price = math.random(0, 0)},
        {Name = "Clique", Value = "clique", Price = math.random(0, 0)},
        {Name = "Coquette", Value = "coquette3", Price = math.random(0, 0)},
        {Name = "Deviant", Value = "deviant", Price = math.random(0, 0)},
        {Name = "Dominator", Value = "dominator", Price = math.random(0, 0)},
        {Name = "DominatorRS", Value = "dominator3", Price = math.random(0, 0)},
        {Name = "Dukes", Value = "dukes", Price = math.random(0, 0)},
        {Name = "Faction", Value = "faction", Price = math.random(0, 0)},
        {Name = "Ellie", Value = "ellie", Price = math.random(0, 0)},
        {Name = "Gauntlet", Value = "gauntlet", Price = math.random(0, 0)},
        {Name = "Hermes", Value = "hermes", Price = math.random(0, 0)},
        {Name = "Hotknife", Value = "hotknife", Price = math.random(0, 0)},
        {Name = "Hustler", Value = "hustler", Price = math.random(0, 0)},
        {Name = "Impaler", Value = "impaler", Price = math.random(0, 0)},
        {Name = "Imperator", Value = "imperator", Price = math.random(0, 0)},
        {Name = "Lurcher", Value = "lurcher", Price = math.random(0, 0)},
        {Name = "Moonbeam", Value = "moonbeam", Price = math.random(0, 0)},
        {Name = "Nighshade", Value = "nightshade", Price = math.random(0, 0)},
        {Name = "Phoenix", Value = "phoenix", Price = math.random(0, 0)},
        {Name = "Picador", Value = "picador", Price = math.random(0, 0)},
        {Name = "RatLoader", Value = "ratloader2", Price = math.random(0, 0)},
        {Name = "Ruiner", Value = "ruiner", Price = math.random(0, 0)},
        {Name = "SabreGT", Value = "sabregt", Price = math.random(0, 0)},
        {Name = "Slamvan", Value = "slamvan", Price = math.random(0, 0)},
        {Name = "Stalion", Value = "stalion", Price = math.random(0, 0)},
        {Name = "Tampa", Value = "tampa", Price = math.random(0, 0)},
        {Name = "Tulip", Value = "tulip", Price = math.random(0, 0)},
        {Name = "Vamos", Value = "vamos", Price = math.random(0, 0)},
        {Name = "Vigero", Value = "vigero", Price = math.random(0, 0)},
        {Name = "Virgo", Value = "virgo", Price = math.random(0, 0)},
        {Name = "Voodoo", Value = "voodoo", Price = math.random(0, 0)},
        {Name = "Yosemite", Value = "yosemite", Price = math.random(0, 0)},
    }, 
    Vans = {
        {Name = "Bison", Value = "bison", Price = math.random(0, 0)},
        {Name = "BobcatXL", Value = "bobcatxl", Price = math.random(0, 0)},
        {Name = "Burrito", Value = "burrito", Price = math.random(0, 0)},
        {Name = "Camper", Value = "camper", Price = math.random(0, 0)},
        {Name = "Journey", Value = "journey", Price = math.random(0, 0)},
        {Name = "Minivan", Value = "minivan", Price = math.random(0, 0)},
        {Name = "Paradise", Value = "paradise", Price = math.random(0, 0)},
        {Name = "Pony", Value = "pony", Price = math.random(0, 0)},
        {Name = "Rumpo", Value = "rumpo", Price = math.random(0, 0)},
        {Name = "Speedo", Value = "speedo", Price = math.random(0, 0)},
        {Name = "Surfer", Value = "surfer", Price = math.random(0, 0)},
        {Name = "Youge", Value = "youga", Price = math.random(0, 0)},
    }, 
    Suv = {
        {Name = "Baller", Value = "baller", Price = math.random(0, 0)},
        {Name = "BallerRS", Value = "baller2", Price = math.random(0, 0)},
        {Name = "BJXL", Value = "bjxl", Price = math.random(0, 0)},
        {Name = "Cavalcade", Value = "cavalcade", Price = math.random(0, 0)},
        {Name = "Contender", Value = "contender", Price = math.random(0, 0)},
        {Name = "Dubsta", Value = "dubsta", Price = math.random(0, 0)},
        {Name = "FQ2", Value = "fq2", Price = math.random(0, 0)},
        {Name = "Granger", Value = "granger", Price = math.random(0, 0)},
        {Name = "Gresley", Value = "gresley", Price = math.random(0, 0)},
        {Name = "Habanero", Value = "habanero", Price = math.random(0, 0)},
        {Name = "Huntley", Value = "huntley", Price = math.random(0, 0)},
        {Name = "Landstalker", Value = "landstalker", Price = math.random(0, 0)},
        {Name = "Mesa", Value = "mesa", Price = math.random(0, 0)},
        {Name = "Novak", Value = "novak", Price = math.random(0, 0)},
        {Name = "Patriot", Value = "patriot", Price = math.random(0, 0)},
        {Name = "Radi", Value = "radi", Price = math.random(0, 0)},
        {Name = "Rebla", Value = "rebla", Price = math.random(0, 0)},
        {Name = "Rocotp", Value = "rocoto", Price = math.random(0, 0)},
        {Name = "Semimole", Value = "seminole", Price = math.random(0, 0)},
        {Name = "Serrano", Value = "serrano", Price = math.random(0, 0)},
        {Name = "Toros", Value = "toros", Price = math.random(0, 0)},
        {Name = "XLS", Value = "xls", Price = math.random(0, 0)},
    }, 
    OffRoad = {
        {Name = "BFinjection", Value = "bfinjection", Price = math.random(0, 0)},
        {Name = "Bifta", Value = "bifta", Price = math.random(0, 0)},
        {Name = "Blazer", Value = "blazer", Price = math.random(0, 0)},
        {Name = "Blazer street", Value = "blazer4", Price = math.random(0, 0)},
        {Name = "Bodhi", Value = "bodhi2", Price = math.random(0, 0)},
        {Name = "Brawler", Value = "brawler", Price = math.random(0, 0)},
        {Name = "Brutus", Value = "brutus", Price = math.random(0, 0)},
        {Name = "Caracara", Value = "caracara", Price = math.random(0, 0)},
        {Name = "Caracara custom", Value = "caracara2", Price = math.random(0, 0)},
        {Name = "DLoader", Value = "dloader", Price = math.random(0, 0)},
        {Name = "Dubsta", Value = "dubsta3", Price = math.random(0, 0)},
        {Name = "Dune", Value = "dune", Price = math.random(0, 0)},
        {Name = "Everon", Value = "everon", Price = math.random(0, 0)},
        {Name = "Freecrawler", Value = "freecrawler", Price = math.random(0, 0)},
        {Name = "Hellion", Value = "hellion", Price = math.random(0, 0)},
        {Name = "Kalahari", Value = "kalahari", Price = math.random(0, 0)},
        {Name = "Kamacho", Value = "kamacho", Price = math.random(0, 0)},
        {Name = "Mesa", Value = "mesa3", Price = math.random(0, 0)},
        {Name = "Outlaw", Value = "outlaw", Price = math.random(0, 0)},
        {Name = "RancherXL", Value = "rancherxl", Price = math.random(0, 0)},
        {Name = "Rebel", Value = "rebel", Price = math.random(0, 0)},
        {Name = "Riata", Value = "riata", Price = math.random(0, 0)},
        {Name = "Sandking", Value = "sandking", Price = math.random(0, 0)},
        {Name = "SandkingXL", Value = "sandking2", Price = math.random(0, 0)},
        {Name = "Vagrant", Value = "vagrant", Price = math.random(0, 0)},
    }, 
    Coupe = {
        {Name = "Cogcabrio", Value = "cogcabrio", Price = math.random(0, 0)},
        {Name = "Exemplar", Value = "exemplar", Price = math.random(0, 0)},
        {Name = "F620", Value = "f620", Price = math.random(0, 0)},
        {Name = "Felon", Value = "felon", Price = math.random(0, 0)},
        {Name = "Felon Cabriolé", Value = "felon2", Price = math.random(0, 0)},
        {Name = "Jackal", Value = "jackal", Price = math.random(0, 0)},
        {Name = "Oracle", Value = "oracle", Price = math.random(0, 0)},
        {Name = "Sentinel", Value = "sentinel", Price = math.random(0, 0)},
        {Name = "Sentinel Cabriolé", Value = "sentinel2", Price = math.random(0, 0)},
        {Name = "Zion", Value = "zion", Price = math.random(0, 0)},
        {Name = "Zion Cabriolé", Value = "zion2", Price = math.random(0, 0)},
    }, 
    Compacts = {
        {Name = "Abso", Value = "asbo", Price = math.random(1000, 3000)},
        {Name = "Blista", Value = "blista", Price = math.random(1000, 3000)},
        {Name = "Brioso", Value = "brioso", Price = math.random(1000, 3000)},
        {Name = "Club", Value = "club", Price = math.random(1000, 3000)},
        {Name = "Dilettante", Value = "dilettante", Price = math.random(1000, 3000)},
        {Name = "Kanjo", Value = "kanjo", Price = math.random(1000, 3000)},
        {Name = "Issi", Value = "issi2", Price = math.random(1000, 3000)},
        {Name = "Issi RS", Value = "issi7", Price = math.random(1000, 3000)},
        {Name = "Panto", Value = "panto", Price = math.random(1000, 3000)},
        {Name = "Prairie", Value = "prairie", Price = math.random(1000, 3000)},
        {Name = "Rhapsody", Value = "rhapsody", Price = math.random(1000, 3000)},
    }, 
    Moto = {
        {Name = "Akuma", Value = "akuma", Price = math.random(0, 0)},
        {Name = "Avarus", Value = "avarus", Price = math.random(0, 0)},
        {Name = "Bagger", Value = "bagger", Price = math.random(0, 0)},
        {Name = "Bati801", Value = "bati", Price = math.random(0, 0)},
        {Name = "Bf400", Value = "bf400", Price = math.random(0, 0)},
        {Name = "CarbonRS", Value = "carbonrs", Price = math.random(0, 0)},
        {Name = "Chimera", Value = "chimera", Price = math.random(0, 0)},
        {Name = "Cliffhanger", Value = "cliffhanger", Price = math.random(0, 0)},
        {Name = "Daemon", Value = "daemon", Price = math.random(0, 0)},
        {Name = "Defiler", Value = "defiler", Price = math.random(0, 0)},
        {Name = "Diabolus", Value = "diablous", Price = math.random(0, 0)},
        {Name = "Diabolus Custom", Value = "diablous2", Price = math.random(0, 0)},
        {Name = "Double T", Value = "double", Price = math.random(0, 0)},
        {Name = "Enduro", Value = "enduro", Price = math.random(0, 0)},
        {Name = "Esskey", Value = "esskey", Price = math.random(0, 0)},
        {Name = "Faggio", Value = "faggio", Price = math.random(0, 0)},
        {Name = "Faggio MOD", Value = "faggio3", Price = math.random(0, 0)},
        {Name = "FCR", Value = "fcr", Price = math.random(0, 0)},
        {Name = "Gargoyle", Value = "gargoyle", Price = math.random(0, 0)},
        {Name = "Hakuchou", Value = "hakuchou", Price = math.random(0, 0)},
        {Name = "Hexer", Value = "hexer", Price = math.random(0, 0)},
        {Name = "Innovation", Value = "innovation", Price = math.random(0, 0)},
        {Name = "Lectro", Value = "lectro", Price = math.random(0, 0)},
        {Name = "Manchez", Value = "manchez", Price = math.random(0, 0)},
        {Name = "Nemesis", Value = "nemesis", Price = math.random(0, 0)},
        {Name = "Nightblade", Value = "nightblade", Price = math.random(0, 0)},
        {Name = "PCJ", Value = "pcj", Price = math.random(0, 0)},
        {Name = "Ruffian", Value = "ruffian", Price = math.random(0, 0)},
        {Name = "Rocket", Value = "rrocket", Price = math.random(0, 0)},
        {Name = "Sanchez", Value = "sanchez2", Price = math.random(0, 0)},
        {Name = "Sanctus", Value = "sanctus", Price = math.random(0, 0)},
        {Name = "Stryder", Value = "stryder", Price = math.random(0, 0)},
        {Name = "Thrust", Value = "thrust", Price = math.random(0, 0)},
        {Name = "Vader", Value = "vader", Price = math.random(0, 0)},
        {Name = "Vindicator", Value = "vindicator", Price = math.random(0, 0)},
        {Name = "Vortex", Value = "vortex", Price = math.random(0, 0)},
        {Name = "Wolfsbane", Value = "wolfsbane", Price = math.random(0, 0)},
        {Name = "Zombie", Value = "zombiea", Price = math.random(0, 0)},
    }, 
    Velo = {
        {Name = "BMX", Value = "bmx", Price = math.random(0, 0)},
        {Name = "Cruiser", Value = "cruiser", Price = math.random(0, 0)},
        {Name = "Fixter", Value = "fixter", Price = math.random(0, 0)},
        {Name = "Scorcher", Value = "scorcher", Price = math.random(0, 0)},
        {Name = "TriBike", Value = "tribike3", Price = math.random(0, 0)},
    }
  }