MenuColour = {
	Banner = {
		R = 13,
		G = 24,
		B = 33,
		A = 255,
    },
    Background = {
        R = 13,
        G = 24,
        B = 33,
        A = 200,
    },
	Selection = {
		R = 123,
		G = 137,
		B = 138,
		A = 127.5,
	},
	Desc = {
		R = 13,
		G = 24,
		B = 33,
		A = 150,
	},
	Txt = {
		R = 191,
		G = 204,
		B = 148,
		A = 255,
	},
}
MenuFont = {
	Txt = 6,
	Title = 6,
	SubTitle = 6,
	Desc = 6,
}
FontPos = {
    [0] = {
        Banner = {
            Title = {X = 215, Y = 40, Scale = 0.7},
            Sub = {X = 85, Y = 5, Scale = 0.4},
        },
        Txt = {
            X = 6, Y = 1,Scale = 0.4,
        },
    },
    [1] = {
        Banner = {
            Title = {X = 215, Y = 30, Scale = 0.9},
            Sub = {X = 80, Y = 0, Scale = 0.5},
        },
        Txt = {
            X = 6, Y = 1,Scale = 0.6,
        },
    },
    [2] = {
        Banner = {
            Title = {X = 215, Y = 30, Scale = 0.9},
            Sub = {X = 80, Y = 0, Scale = 0.5},
        },
        Txt = {
            X = 6, Y = 1,Scale = 0.5,
        },
    },
    [4] = {
        Banner = {
            Title = {X = 215, Y = 30, Scale = 0.9},
            Sub = {X = 65, Y = 0, Scale = 0.5},
        },
        Txt = {
            X = 6, Y = 1,Scale = 0.5,
        },
    },
    [6] = {
        Banner = {
            Title = {X = 215, Y = 30, Scale = 0.9},
            Sub = {X = 65, Y = 0, Scale = 0.5},
        },
        Txt = {
            X = 6, Y = 1,Scale = 0.5,
        },
    },
    [7] = {
        Banner = {
            Title = {X = 215, Y = 30, Scale = 0.9},
            Sub = {X = 85, Y = 5, Scale = 0.4},
        },
        Txt = {
            X = 6, Y = 7,Scale = 0.45,
        },
    },
}

RegisterNetEvent("RageUI:Set:Setting")
AddEventHandler("RageUI:Set:Setting", function(Setting)
    Result = json.decode(Setting)
    MenuColour = Result.Colour
    MenuFont = Result.Style
end)

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 21/04/2019 21:20
---

---CreateMenu
---@param Title string
---@param Subtitle string
---@param X number
---@param Y number
---@param TextureDictionary string
---@param TextureName string
---@param R number
---@param G number
---@param B number
---@param A number
---@return RageUIMenus
---@public
function RageUI.CreateMenu(Title, Subtitle, X, Y, TextureDictionary, TextureName, R, G, B, A)

    ---@type table
    local Menu = {}
    Menu.Display = {};

    Menu.InstructionalButtons = {}

    Menu.Display.Header = true;
    Menu.Display.Glare = true;
    Menu.Display.Subtitle = true;
    Menu.Display.Background = true;
    Menu.Display.Navigation = true;
    Menu.Display.InstructionalButton = true;

    Menu.Title = Title or ""
    Menu.Subtitle = Subtitle or nil
    Menu.SubtitleHeight = -37
    Menu.Description = nil
    Menu.DescriptionHeight = RageUI.Settings.Items.Description.Background.Height
    Menu.X = X or 0
    Menu.Y = Y or 0
    Menu.Parent = nil
    Menu.WidthOffset = 0
    Menu.Open = false
    Menu.Controls = RageUI.Settings.Controls
    Menu.Index = 1
    Menu.Sprite = { Dictionary = TextureDictionary or "root_cause", Texture = TextureName or "interaction_bgd", Color = { R = R, G = G, B = B, A = A } }
    Menu.Rectangle = nil
    Menu.Pagination = { Minimum = 1, Maximum = 10, Total = 10 }
    Menu.Safezone = true
    Menu.SafeZoneSize = nil
    Menu.EnableMouse = false
    Menu.Options = 0
    Menu.Closable = true
    Menu.InstructionalScaleform = RequestScaleformMovie("INSTRUCTIONAL_BUTTONS")
    Menu.InitScaleform = false
    Menu.CursorStyle = 1

    if string.starts(Menu.Subtitle, "~") then
        Menu.PageCounterColour = string.sub(Menu.Subtitle, 1, 3)
    else
        Menu.PageCounterColour = ""
    end

    if Menu.Subtitle ~= "" then
        local SubtitleLineCount = GetLineCount(Menu.Subtitle, Menu.X + RageUI.Settings.Items.Subtitle.Text.X, Menu.Y + RageUI.Settings.Items.Subtitle.Text.Y, 0, RageUI.Settings.Items.Subtitle.Text.Scale, 245, 245, 245, 255, nil, false, false, RageUI.Settings.Items.Subtitle.Background.Width + Menu.WidthOffset)

        if SubtitleLineCount > 1 then
            Menu.SubtitleHeight = 18 * SubtitleLineCount
        else
            Menu.SubtitleHeight = 0
        end
    end
    Citizen.CreateThread(function()
        if not HasScaleformMovieLoaded(Menu.InstructionalScaleform) then
            Menu.InstructionalScaleform = RequestScaleformMovie("INSTRUCTIONAL_BUTTONS")
            while not HasScaleformMovieLoaded(Menu.InstructionalScaleform) do
                Citizen.Wait(0)
            end
        end
        local ScaleformMovie = RequestScaleformMovie("MP_MENU_GLARE")
        while not HasScaleformMovieLoaded(ScaleformMovie) do
            Citizen.Wait(0)
        end
    end)

    return setmetatable(Menu, RageUI.Menus)
end

---CreateSubMenu
---@param ParentMenu function
---@param Title string
---@param Subtitle string
---@param X number
---@param Y number
---@param TextureDictionary string
---@param TextureName string
---@param R number
---@param G number
---@param B number
---@param A number
---@return RageUIMenus
---@public
function RageUI.CreateSubMenu(ParentMenu, Title, Subtitle, X, Y, TextureDictionary, TextureName, R, G, B, A)
    if ParentMenu ~= nil then
        if ParentMenu() then
            local Menu = RageUI.CreateMenu(Title or ParentMenu.Title, Subtitle or ParentMenu.Subtitle, X or ParentMenu.X, Y or ParentMenu.Y)
            Menu.Parent = ParentMenu
            Menu.WidthOffset = ParentMenu.WidthOffset
            Menu.Safezone = ParentMenu.Safezone
            if ParentMenu.Sprite then
                Menu.Sprite = { Dictionary = TextureDictionary or ParentMenu.Sprite.Dictionary, Texture = TextureName or ParentMenu.Sprite.Texture, Color = { R = R or ParentMenu.Sprite.Color.R, G = G or ParentMenu.Sprite.Color.G, B = B or ParentMenu.Sprite.Color.B, A = A or ParentMenu.Sprite.Color.A } }
            else
                Menu.Rectangle = ParentMenu.Rectangle
            end
            return setmetatable(Menu, RageUI.Menus)
        else
            return nil
        end
    else
        return nil
    end
end

function RageUI.Menus:DisplayHeader(boolean)
    self.Display.Header = boolean;
    return self.Display.Header;
end

function RageUI.Menus:DisplayGlare(boolean)
    self.Display.Glare = boolean;
    return self.Display.Glare;
end

function RageUI.Menus:DisplaySubtitle(boolean)
    self.Display.Subtitle = boolean;
    return self.Display.Subtitle;
end

function RageUI.Menus:DisplayNavigation(boolean)
    self.Display.Navigation = boolean;
    return self.Display.Navigation;
end

function RageUI.Menus:DisplayInstructionalButton(boolean)
    self.Display.InstructionalButton = boolean;
    return self.Display.InstructionalButton;
end

function RageUI.Menus:SetTitle(Title)
    self.Title = Title
end

function RageUI.Menus:SetSizeWidth(Value)
    local witdh
    if Value >= 0 and Value <= 1000 then
        witdh = Value
    else
        witdh = 100
    end
    self.WidthOffset = witdh
end

function RageUI.Menus:GetStyleSize()
    if (self.WidthOffset == 100) then
        return "RageUI"
    elseif (self.WidthOffset == 0) then
        return "NativeUI";
    else
        return self.WidthOffset;
    end
end

function RageUI.Menus:SetCursorStyle(Int)
    self.CursorStyle = Int or 1 or 0
    SetMouseCursorSprite(Int)
end

function RageUI.Menus:ResetCursorStyle()
    self.CursorStyle = 1
    SetMouseCursorSprite(1)
end

function RageUI.Menus:UpdateCursorStyle()
    SetMouseCursorSprite(self.CursorStyle)
end

function RageUI.Menus:RefreshIndex()
    self.Index = 1
end

function RageUI.Menus:SetSubtitle(Subtitle)
    self.Subtitle = Subtitle or self.Subtitle
    if string.starts(self.Subtitle, "~") then
        self.PageCounterColour = string.sub(self.Subtitle, 1, 3)
    else
        self.PageCounterColour = ""
    end
    if self.Subtitle ~= "" then
        local SubtitleLineCount = GetLineCount(self.Subtitle, self.X + RageUI.Settings.Items.Subtitle.Text.X, self.Y + RageUI.Settings.Items.Subtitle.Text.Y, 0, RageUI.Settings.Items.Subtitle.Text.Scale, 245, 245, 245, 255, nil, false, false, RageUI.Settings.Items.Subtitle.Background.Width + self.WidthOffset)

        if SubtitleLineCount > 1 then
            self.SubtitleHeight = 18 * SubtitleLineCount
        else
            self.SubtitleHeight = 0
        end

    else
        self.SubtitleHeight = -37
    end
end

function RageUI.Menus:SetPageCounter(Subtitle)
    self.PageCounter = Subtitle
end

function RageUI.Menus:EditSpriteColor(R,G,B,A)
    if self.Sprite.Dictionary == "root_cause" then
        self.Sprite.Color = { R = tonumber(R) or 255, G = tonumber(G) or 255, B = tonumber(B) or 255, A = tonumber(A) or 255 }
    end
end

function RageUI.Menus:SetPosition(X, Y)
    self.X = tonumber(X) or self.X
    self.Y = tonumber(Y) or self.Y
end

function RageUI.Menus:SetTotalItemsPerPage(Value)
    self.Pagination.Total = Value;
    self.Pagination.Maximum = Value;

end

function RageUI.Menus:SetRectangleBanner(R, G, B, A)
    self.Rectangle = { R = tonumber(R) or 255, G = tonumber(G) or 255, B = tonumber(B) or 255, A = tonumber(A) or 255 }
    self.Sprite = nil
end

function RageUI.Menus:SetSpriteBanner(TextureDictionary, Texture)
    self.Sprite = { Dictionary = TextureDictionary or "root_cause", Texture = Texture or "interaction_bgd" }
    self.Rectangle = nil
end

function RageUI.Menus:Closable(boolean)
    if type(boolean) == "boolean" then
        self.Closable = boolean
    else
        error("Type is not boolean")
    end
end

function RageUI.Menus:AddInstructionButton(button)
    if type(button) == "table" and #button == 2 then
        table.insert(self.InstructionalButtons, button)
        self.UpdateInstructionalButtons(true);
    end
end

function RageUI.Menus:RemoveInstructionButton(button)
    if type(button) == "table" then
        for i = 1, #self.InstructionalButtons do
            if button == self.InstructionalButtons[i] then
                table.remove(self.InstructionalButtons, i)
                self.UpdateInstructionalButtons(true);
                break
            end
        end
    else
        if tonumber(button) then
            if self.InstructionalButtons[tonumber(button)] then
                table.remove(self.InstructionalButtons, tonumber(button))
                self.UpdateInstructionalButtons(true);
            end
        end
    end
end

function RageUI.Menus:UpdateInstructionalButtons(Visible)
    if not Visible then
        return
    end
    BeginScaleformMovieMethod(self.InstructionalScaleform, "CLEAR_ALL")
    EndScaleformMovieMethod()

    BeginScaleformMovieMethod(self.InstructionalScaleform, "TOGGLE_MOUSE_BUTTONS")
    ScaleformMovieMethodAddParamInt(0)
    EndScaleformMovieMethod()

    BeginScaleformMovieMethod(self.InstructionalScaleform, "CREATE_CONTAINER")
    EndScaleformMovieMethod()

    BeginScaleformMovieMethod(self.InstructionalScaleform, "SET_DATA_SLOT")
    ScaleformMovieMethodAddParamInt(0)
    PushScaleformMovieMethodParameterButtonName(GetControlInstructionalButton(2, 176, 0))
    PushScaleformMovieMethodParameterString(GetLabelText("HUD_INPUT2"))
    EndScaleformMovieMethod()

    if self.Closable then
        BeginScaleformMovieMethod(self.InstructionalScaleform, "SET_DATA_SLOT")
        ScaleformMovieMethodAddParamInt(1)
        PushScaleformMovieMethodParameterButtonName(GetControlInstructionalButton(2, 177, 0))
        PushScaleformMovieMethodParameterString(GetLabelText("HUD_INPUT3"))
        EndScaleformMovieMethod()
    end

    local count = 2

    if (self.InstructionalButtons ~= nil) then
        for i = 1, #self.InstructionalButtons do
            if self.InstructionalButtons[i] then
                if #self.InstructionalButtons[i] == 2 then
                    BeginScaleformMovieMethod(self.InstructionalScaleform, "SET_DATA_SLOT")
                    ScaleformMovieMethodAddParamInt(count)
                    PushScaleformMovieMethodParameterButtonName(self.InstructionalButtons[i][1])
                    PushScaleformMovieMethodParameterString(self.InstructionalButtons[i][2])
                    EndScaleformMovieMethod()
                    count = count + 1
                end
            end
        end
    end

    BeginScaleformMovieMethod(self.InstructionalScaleform, "DRAW_INSTRUCTIONAL_BUTTONS")
    ScaleformMovieMethodAddParamInt(-1)
    EndScaleformMovieMethod()
end

RegisterNetEvent("RageUI:Update:Colour:Banner")
AddEventHandler("RageUI:Update:Colour:Banner", function(Colour)
    if Colour.R then
        if MenuColour.Banner.R + 1 ~= Colour.R then
            MenuColour.Banner.R = 1
        end
        MenuColour.Banner.R = Colour.R
    end
    if Colour.G then
        if MenuColour.Banner.G + 1 ~= Colour.G then
            MenuColour.Banner.G = 1
        end
        MenuColour.Banner.G = Colour.G
    end
    if Colour.B then
        if MenuColour.Banner.B + 1 ~= Colour.B then
            MenuColour.Banner.B = 1
        end
        MenuColour.Banner.B = Colour.B
    end
    if Colour.A then
        if MenuColour.Banner.A + 1 ~= Colour.A then
            MenuColour.Banner.A = 1
        end
        MenuColour.Banner.A = Colour.A
    end
end)

RegisterNetEvent("RageUI:Update:Colour:Background")
AddEventHandler("RageUI:Update:Colour:Background", function(Colour)
    if Colour.R then
        MenuColour.Background.R = Colour.R
    end
    if Colour.G then
        MenuColour.Background.G = Colour.G
    end
    if Colour.B then
        MenuColour.Background.B = Colour.B
    end
    if Colour.A then
        MenuColour.Background.A = Colour.A
    end
end)

RegisterNetEvent("RageUI:Update:Colour:Txt")
AddEventHandler("RageUI:Update:Colour:Txt", function(Colour)
    if Colour.R then
        MenuColour.Txt.R = Colour.R
    end
    if Colour.G then
        MenuColour.Txt.G = Colour.G
    end
    if Colour.B then
        MenuColour.Txt.B = Colour.B
    end
    if Colour.A then
        MenuColour.Txt.A = Colour.A
    end
end)

RegisterNetEvent("RageUI:Update:Colour:Desc")
AddEventHandler("RageUI:Update:Colour:Desc", function(Colour)
    if Colour.R then
        MenuColour.Desc.R = Colour.R
    end
    if Colour.G then
        MenuColour.Desc.G = Colour.G
    end
    if Colour.B then
        MenuColour.Desc.B = Colour.B
    end
    if Colour.A then
        MenuColour.Desc.A = Colour.A
    end
end)

RegisterNetEvent("RageUI:Update:Colour:Selection")
AddEventHandler("RageUI:Update:Colour:Selection", function(Colour)
    if Colour.R then
        MenuColour.Selection.R = Colour.R
    end
    if Colour.G then
        MenuColour.Selection.G = Colour.G
    end
    if Colour.B then
        MenuColour.Selection.B = Colour.B
    end
    if Colour.A then
        MenuColour.Selection.A = Colour.A
    end
end)

RegisterNetEvent("RageUI:Update:Style:Txt")
AddEventHandler("RageUI:Update:Style:Txt", function(Font)
    MenuFont.Txt = Font
end)

RegisterNetEvent("RageUI:Update:Style:Title")
AddEventHandler("RageUI:Update:Style:Title", function(Font)
    MenuFont.Title = Font
end)

RegisterNetEvent("RageUI:Update:Style:SubTitle")
AddEventHandler("RageUI:Update:Style:SubTitle", function(Font)
    MenuFont.SubTitle = Font
end)

RegisterNetEvent("RageUI:Update:Style:Desc")
AddEventHandler("RageUI:Update:Style:Desc", function(Font)
    MenuFont.Desc = Font
end)