Config = {}

Config.Price = {
	--Tatoo--
	Head = 1000,
	Neck = 750,
	Chest = 750,
	Back = 1000,
	ArmsLegs = 500,
	Shoulder = 600,
	Stomach = 800,
	Hipster = 1250,
	Mp = 350,
	Noel = 550,
	Luxe = 2500,
	LowRider = 450,
	Stunt = 850,
	Biker = 250,
	Export = 1700,
	Gun = 950,
	--Mask--
	Mask = 150,
	--Clothe--
	Tenue = 100,
	Clothe = 25,
	--Weapon--
	Chargeur = 150,
}

Config.Market = {
	{x = 373.875,   y = 325.896,  z = 102.566},
    {x = 2557.458,  y = 382.282,  z = 107.622},
    {x = -3038.939, y = 585.954,  z = 6.908},
    {x = -3241.927, y = 1001.462, z = 11.830},
    {x = 547.431,   y = 2671.710, z = 41.156},
    {x = 1961.464,  y = 3740.672, z = 31.343},
    {x = 2678.916,  y = 3280.671, z = 54.241},
    {x = 1729.216,  y = 6414.131, z = 34.037},
    {x = 1135.808,  y = -982.281,  z = 45.415},
    {x = -1222.915, y = -906.983,  z = 11.326},
    {x = -1487.553, y = -379.107,  z = 39.163},
    {x = -2968.243, y = 390.910,   z = 14.043},
    {x = 1166.024,  y = 2708.930,  z = 37.157},
    {x = 1392.562,  y = 3604.684,  z = 33.980},
    {x = -48.519,   y = -1757.514, z = 28.421},
    {x = 1163.373,  y = -323.801,  z = 68.205},
    {x = -707.501,  y = -914.260,  z = 18.215},
    {x = 24.381, y = -1347.793, z = 29.497},
    {x = -1820.523, y = 792.518,   z = 137.118},
    {x = 1698.388,  y = 4924.404,  z = 41.063},
}
Config.Market.Items = {
	{Label = "Pain", Value = "bread", Price = 15, MaxNbr = 5},
	{Label = "Eau", Value = "water", Price = 15, MaxNbr = 5},
}

Config.Weapon = {
	{x = -662.1, y = -935.3, z = 20.8},
	{x = 810.2, y = -2157.3, z = 28.6},
	{x = 1693.4, y = 3759.5, z = 33.7},
	{x = -330.2, y = 6083.8, z = 30.4},
	{x = 252.3, y = -50.0, z = 68.9},
	{x = 22.0, y = -1107.2, z = 28.8},
	{x = 2567.6, y = 294.3, z = 107.7},
	{x = -1117.5, y = 2698.6, z = 17.5},
	{x = 842.4, y = -1033.4, z = 27.1},
}
Config.Weapon.Items = {
        Blanches = {
            {Label = 'Lampe Torche', Value = 'weapon_flashlight', Price = 200},
            {Label = 'Couteau Papillon', Value = 'weapon_switchblade', Price = 600},
            {Label = 'Poing américain', Value = 'weapon_knuckle', Price = 800},
        },

        Feu = {
            {Label = 'Pistolet Pétoire', Value = 'WEAPON_SNSPISTOL', Price = 2500},
            {Label = 'Pistolet 9mm', Value = 'weapon_pistol', Price = 5000},
        },
}

Config.Clothe = {
	{x = 72.254, y = -1399.102,z = 28.376},
	{x = -703.776, y = -152.258, z = 36.415},
	{x = -167.863, y = -298.969, z = 38.733},
	{x = 428.694, y = -800.106, z = 28.491},
	{x = -829.413, y = -1073.710, z = 10.328},
	{x = -1447.797, y = -242.461, z = 48.820},
	{x = 11.632, y = 6514.224, z = 30.877},
	{x = 123.646, y = -219.440, z = 53.557},
	{x = 1696.291, y = 4829.312, z = 41.063},
	{x = 618.093, y = 2759.629, z = 41.088},
	{x = 1190.550, y = 2713.441, z = 37.222},
	{x = -1193.429, y = -772.262, z = 16.324},
	{x = -3172.496, y = 1048.133, z = 19.863},
	{x = -1108.441, y = 2708.923, z = 18.107},
}

Config.Mask = {
	{x = -1337.261, y = -1277.351, z = 4.880},
}

Config.Tatoo = {
	{x = 1322.6, y = -1651.9, z = 51.2},
	{x = -1153.6, y = -1425.6, z = 4.9},
	{x = 322.1, y = 180.4, z = 103.5},
	{x = -3170.0, y = 1075.0, z = 20.8},
	{x = 1864.6, y =  3747.7, z = 33.0},
	{x = -293.7, y = 6200.0, z = 31.4},
}

Config.HeadTatooList = {
	{Name = "#1", Hash = 'MP_MP_Biker_Tat_009_F', Value = "mpbiker_overlays"},
	{Name = "#2", Hash = 'MP_MP_Biker_Tat_038_F', Value = "mpbiker_overlays"},
	{Name = "#3", Hash = 'MP_MP_Biker_Tat_051_F', Value = "mpbiker_overlays"},
	{Name = "#4", Hash = 'MP_MP_Stunt_Tat_000_F', Value = "mpstunt_overlays"},
	{Name = "#5", Hash = 'MP_MP_Stunt_tat_004_F', Value = "mpstunt_overlays"},
	{Name = "#6", Hash = 'MP_MP_Stunt_tat_006_F', Value = "mpstunt_overlays"},
	{Name = "#7", Hash = 'MP_MP_Stunt_tat_017_F', Value = "mpstunt_overlays"},
	{Name = "#8", Hash = 'MP_MP_Stunt_tat_042_F', Value = "mpstunt_overlays"},
	{Name = "#9", Hash = 'MP_Xmas2_F_Tat_007', Value = "mpchristmas2_overlays"},
	{Name = "#10", Hash = 'MP_Xmas2_F_Tat_024', Value = "mpchristmas2_overlays"},
	{Name = "#11", Hash = 'MP_Xmas2_F_Tat_025', Value = "mpchristmas2_overlays"},
	{Name = "#12", Hash = 'MP_Xmas2_F_Tat_029', Value = "mpchristmas2_overlays"},
	{Name = "#13", Hash = 'MP_Xmas2_M_Tat_007', Value = "mpchristmas2_overlays"},
	{Name = "#14", Hash = 'MP_Xmas2_M_Tat_024', Value = "mpchristmas2_overlays"},
	{Name = "#15", Hash = 'MP_Xmas2_M_Tat_025', Value = "mpchristmas2_overlays"},
	{Name = "#16", Hash = 'MP_Xmas2_M_Tat_029', Value = "mpchristmas2_overlays"},
	{Name = "#17", Hash = 'MP_Bea_M_Head_000', Value = "mpbeach_overlays"},
	{Name = "#18", Hash = 'MP_Bea_M_Head_001', Value = "mpbeach_overlays"},
	{Name = "#19", Hash = 'MP_Bea_M_Head_002', Value = "mpbeach_overlays"},
}

Config.NeckTatooList = {
	{Name = "#1", Hash = 'MP_Buis_F_Neck_000', Value = "mpbusiness_overlays"},
	{Name = "#2", Hash = 'MP_Buis_M_Neck_000', Value = "mpbusiness_overlays"},
	{Name = "#3", Hash = 'MP_Buis_M_Neck_001', Value = "mpbusiness_overlays"},
	{Name = "#4", Hash = 'MP_Buis_F_Neck_001', Value = "mpbusiness_overlays"},
	{Name = "#5", Hash = 'MP_Buis_M_Neck_002', Value = "mpbusiness_overlays"},
	{Name = "#6", Hash = 'MP_Buis_M_Neck_003', Value = "mpbusiness_overlays"},
	{Name = "#7", Hash = 'MP_Bea_F_Neck_000', Value = "mpbeach_overlays"},
	{Name = "#8", Hash = 'MP_Bea_M_Neck_000', Value = "mpbeach_overlays"},
	{Name = "#9", Hash = 'MP_Bea_M_Neck_001', Value = "mpbeach_overlays"},
}

Config.ChestTatooList = {
	{Name = "#1", Hash = 'MP_Buis_M_Chest_000', Value = "mpbusiness_overlays"},
	{Name = "#2", Hash = 'MP_Buis_M_Chest_001', Value = "mpbusiness_overlays"},
	{Name = "#3", Hash = 'MP_Buis_F_Chest_000', Value = "mpbusiness_overlays"},
	{Name = "#4", Hash = 'MP_Buis_F_Chest_001', Value = "mpbusiness_overlays"},
	{Name = "#5", Hash = 'MP_Buis_F_Chest_002', Value = "mpbusiness_overlays"},
	{Name = "#6", Hash = 'MP_Bea_F_Chest_000', Value = "mpbeach_overlays"},
	{Name = "#7", Hash = 'MP_Bea_F_Chest_001', Value = "mpbeach_overlays"},
	{Name = "#8", Hash = 'MP_Bea_F_Chest_002', Value = "mpbeach_overlays"},
	{Name = "#9", Hash = 'MP_Bea_M_Chest_000', Value = "mpbeach_overlays"},
	{Name = "#10", Hash = 'MP_Bea_M_Chest_001', Value = "mpbeach_overlays"},
}

Config.BackTatooList = {
	{Name = "#1", Hash = 'MP_Bea_F_Back_000', Value = "mpbeach_overlays"},
	{Name = "#2", Hash = 'MP_Bea_F_Back_001', Value = "mpbeach_overlays"},
	{Name = "#3", Hash = 'MP_Bea_F_Back_002', Value = "mpbeach_overlays"},
	{Name = "#4", Hash = 'MP_Bea_M_Back_000', Value = "mpbeach_overlays"},
	{Name = "#5", Hash = 'MP_Buis_M_Back_000', Value = "mpbusiness_overlays"},
	{Name = "#6", Hash = 'MP_Buis_F_Back_000', Value = "mpbusiness_overlays"},
	{Name = "#7", Hash = 'MP_Buis_F_Back_001', Value = "mpbusiness_overlays"},
	{Name = "#8", Hash = 'MP_Luxe_Tat_022_F', Value = "mpluxe2_overlays"},
	{Name = "#9", Hash = 'MP_Luxe_Tat_029_F', Value = "mpluxe2_overlays"},
}

Config.LArmsTatooList = {
	{Name = "#1", Hash = 'MP_Buis_M_LeftArm_000', Value = "mpbusiness_overlays"},
	{Name = "#2", Hash = 'MP_Buis_M_LeftArm_001', Value = "mpbusiness_overlays"},
	{Name = "#3", Hash = 'MP_Bea_F_LArm_000', Value = "mpbeach_overlays"},
	{Name = "#4", Hash = 'MP_Bea_F_LArm_001', Value = "mpbeach_overlays"},
	{Name = "#5", Hash = 'MP_Bea_M_LArm_000', Value = "mpbeach_overlays"},
	{Name = "#6", Hash = 'MP_Bea_M_LArm_001', Value = "mpbeach_overlays"},
	{Name = "#7", Hash = 'MP_Buis_F_LArm_000', Value = "mpbusiness_overlays"},
	{Name = "#8", Hash = 'MP_Bea_F_LArm_001', Value = "mpluxe_overlays"},
	{Name = "#9", Hash = 'MP_Luxe_Tat_029_F', Value = "mpluxe2_overlays"},
}

Config.RArmsTatooList = {
	{Name = "#1", Hash = 'MP_Bea_F_RArm_001', Value = "mpbeach_overlays"},
	{Name = "#2", Hash = 'MP_Bea_M_RArm_001', Value = "mpbeach_overlays"},
	{Name = "#3", Hash = 'MP_Bea_M_RArm_000', Value = "mpbeach_overlays"},
	{Name = "#4", Hash = 'MP_Buis_F_RArm_000', Value = "mpbusiness_overlays"},
	{Name = "#5", Hash = 'MP_Buis_M_RightArm_000', Value = "mpbusiness_overlays"},
	{Name = "#6", Hash = 'MP_Buis_M_RightArm_001', Value = "mpbusiness_overlays"},
}

Config.ShouldTatooList = {
	{Name = "#1", Hash = 'MP_Bea_F_Should_000', Value = "mpbeach_overlays"},
	{Name = "#2", Hash = 'MP_Bea_F_Should_001', Value = "mpbeach_overlays"},
}

Config.StomachTatooList = {
	{Name = "#1", Hash = 'MP_Bea_F_Stom_000', Value = "mpbeach_overlays"},
	{Name = "#2", Hash = 'MP_Bea_F_Stom_001', Value = "mpbeach_overlays"},
	{Name = "#3", Hash = 'MP_Bea_F_Stom_002', Value = "mpbeach_overlays"},
	{Name = "#4", Hash = 'MP_Bea_M_Stom_000', Value = "mpbeach_overlays"},
	{Name = "#5", Hash = 'MP_Bea_M_Stom_001', Value = "mpbeach_overlays"},
	{Name = "#6", Hash = 'MP_Buis_M_Stomach_000', Value = "mpbusiness_overlays"},
	{Name = "#7", Hash = 'MP_Buis_F_Stom_000', Value = "mpbusiness_overlays"},
	{Name = "#8", Hash = 'MP_Buis_F_Stom_001', Value = "mpbusiness_overlays"},
	{Name = "#9", Hash = 'MP_Buis_F_Stom_002', Value = "mpbusiness_overlays"},
}

Config.LLegTatooList = {
	{Name = "#1", Hash = 'MP_Bea_M_Lleg_000', Value = "mpbeach_overlays"},
	{Name = "#2", Hash = 'MP_Buis_F_LLeg_000', Value = "mpbusiness_overlays"},
}

Config.RLegTatooList = {
	{Name = "#1", Hash = 'MP_Bea_F_RLeg_000', Value = "mpbeach_overlays"},
	{Name = "#2", Hash = 'MP_Bea_M_RLeg_000', Value = "mpbeach_overlays"},
	{Name = "#3", Hash = 'MP_Buis_F_RLeg_000', Value = "mpbusiness_overlays"},
}

Config.HipsterTatooList = {
	{Name = "#1", Hash = 'FM_Hip_M_Tat_000', Value = "mphipster_overlays"},
	{Name = "#2", Hash = 'FM_Hip_M_Tat_001', Value = "mphipster_overlays"},
	{Name = "#3", Hash = 'FM_Hip_M_Tat_002', Value = "mphipster_overlays"},
	{Name = "#4", Hash = 'FM_Hip_M_Tat_003', Value = "mphipster_overlays"},
	{Name = "#5", Hash = 'FM_Hip_M_Tat_004', Value = "mphipster_overlays"},
	{Name = "#6", Hash = 'FM_Hip_M_Tat_005', Value = "mphipster_overlays"},
	{Name = "#7", Hash = 'FM_Hip_M_Tat_006', Value = "mphipster_overlays"},
	{Name = "#8", Hash = 'FM_Hip_M_Tat_007', Value = "mphipster_overlays"},
	{Name = "#9", Hash = 'FM_Hip_M_Tat_008', Value = "mphipster_overlays"},
	{Name = "#10", Hash = 'FM_Hip_M_Tat_009', Value = "mphipster_overlays"},
	{Name = "#11", Hash = 'FM_Hip_M_Tat_010', Value = "mphipster_overlays"},
	{Name = "#12", Hash = 'FM_Hip_M_Tat_011', Value = "mphipster_overlays"},
	{Name = "#13", Hash = 'FM_Hip_M_Tat_012', Value = "mphipster_overlays"},
	{Name = "#14", Hash = 'FM_Hip_M_Tat_013', Value = "mphipster_overlays"},
	{Name = "#15", Hash = 'FM_Hip_M_Tat_014', Value = "mphipster_overlays"},
	{Name = "#16", Hash = 'FM_Hip_M_Tat_015', Value = "mphipster_overlays"},
	{Name = "#17", Hash = 'FM_Hip_M_Tat_016', Value = "mphipster_overlays"},
	{Name = "#18", Hash = 'FM_Hip_M_Tat_017', Value = "mphipster_overlays"},
	{Name = "#19", Hash = 'FM_Hip_M_Tat_018', Value = "mphipster_overlays"},
	{Name = "#20", Hash = 'FM_Hip_M_Tat_019', Value = "mphipster_overlays"},
	{Name = "#21", Hash = 'FM_Hip_M_Tat_020', Value = "mphipster_overlays"},
	{Name = "#22", Hash = 'FM_Hip_M_Tat_021', Value = "mphipster_overlays"},
	{Name = "#23", Hash = 'FM_Hip_M_Tat_022', Value = "mphipster_overlays"},
	{Name = "#24", Hash = 'FM_Hip_M_Tat_023', Value = "mphipster_overlays"},
	{Name = "#25", Hash = 'FM_Hip_M_Tat_024', Value = "mphipster_overlays"},
	{Name = "#26", Hash = 'FM_Hip_M_Tat_025', Value = "mphipster_overlays"},
	{Name = "#27", Hash = 'FM_Hip_M_Tat_026', Value = "mphipster_overlays"},
	{Name = "#28", Hash = 'FM_Hip_M_Tat_027', Value = "mphipster_overlays"},
	{Name = "#29", Hash = 'FM_Hip_M_Tat_028', Value = "mphipster_overlays"},
	{Name = "#30", Hash = 'FM_Hip_M_Tat_029', Value = "mphipster_overlays"},
	{Name = "#31", Hash = 'FM_Hip_M_Tat_030', Value = "mphipster_overlays"},
	{Name = "#32", Hash = 'FM_Hip_M_Tat_031', Value = "mphipster_overlays"},
	{Name = "#33", Hash = 'FM_Hip_M_Tat_032', Value = "mphipster_overlays"},
	{Name = "#34", Hash = 'FM_Hip_M_Tat_033', Value = "mphipster_overlays"},
	{Name = "#35", Hash = 'FM_Hip_M_Tat_034', Value = "mphipster_overlays"},
	{Name = "#36", Hash = 'FM_Hip_M_Tat_035', Value = "mphipster_overlays"},
	{Name = "#37", Hash = 'FM_Hip_M_Tat_036', Value = "mphipster_overlays"},
	{Name = "#38", Hash = 'FM_Hip_M_Tat_037', Value = "mphipster_overlays"},
	{Name = "#39", Hash = 'FM_Hip_M_Tat_038', Value = "mphipster_overlays"},
	{Name = "#40", Hash = 'FM_Hip_M_Tat_039', Value = "mphipster_overlays"},
	{Name = "#41", Hash = 'FM_Hip_M_Tat_040', Value = "mphipster_overlays"},
	{Name = "#42", Hash = 'FM_Hip_M_Tat_041', Value = "mphipster_overlays"},
	{Name = "#43", Hash = 'FM_Hip_M_Tat_042', Value = "mphipster_overlays"},
	{Name = "#44", Hash = 'FM_Hip_M_Tat_043', Value = "mphipster_overlays"},
	{Name = "#45", Hash = 'FM_Hip_M_Tat_044', Value = "mphipster_overlays"},
	{Name = "#46", Hash = 'FM_Hip_M_Tat_045', Value = "mphipster_overlays"},
	{Name = "#47", Hash = 'FM_Hip_M_Tat_046', Value = "mphipster_overlays"},
	{Name = "#48", Hash = 'FM_Hip_M_Tat_047', Value = "mphipster_overlays"},
	{Name = "#49", Hash = 'FM_Hip_M_Tat_048', Value = "mphipster_overlays"},
}

Config.MpTatooList = {
	{Name = "#1", Hash = 'FM_Tat_Award_F_003', Value = "multiplayer_overlays"},
	{Name = "#2", Hash = 'FM_Tat_Award_F_004', Value = "multiplayer_overlays"},
	{Name = "#3", Hash = 'FM_Tat_Award_F_011', Value = "multiplayer_overlays"},
	{Name = "#4", Hash = 'FM_Tat_Award_F_012', Value = "multiplayer_overlays"},
	{Name = "#5", Hash = 'FM_Tat_Award_F_013', Value = "multiplayer_overlays"},
	{Name = "#6", Hash = 'FM_Tat_F_004', Value = "multiplayer_overlays"},
	{Name = "#7", Hash = 'FM_Tat_F_010', Value = "multiplayer_overlays"},
	{Name = "#8", Hash = 'FM_Tat_F_012', Value = "multiplayer_overlays"},
	{Name = "#9", Hash = 'FM_Tat_F_024', Value = "multiplayer_overlays"},
	{Name = "#10", Hash = 'FM_Tat_F_025', Value = "multiplayer_overlays"},
	{Name = "#11", Hash = 'FM_Tat_F_029', Value = "multiplayer_overlays"},
	{Name = "#12", Hash = 'FM_Tat_F_034', Value = "multiplayer_overlays"},
	{Name = "#13", Hash = 'FM_Tat_F_036', Value = "multiplayer_overlays"},
	{Name = "#14", Hash = 'FM_Tat_F_044', Value = "multiplayer_overlays"},
	{Name = "#15", Hash = 'FM_Tat_Award_F_005', Value = "multiplayer_overlays"},
	{Name = "#16", Hash = 'FM_Tat_Award_F_008', Value = "multiplayer_overlays"},
	{Name = "#17", Hash = 'FM_Tat_Award_F_014', Value = "multiplayer_overlays"},
	{Name = "#18", Hash = 'FM_Tat_Award_F_016', Value = "multiplayer_overlays"},
	{Name = "#19", Hash = 'FM_Tat_Award_F_017', Value = "multiplayer_overlays"},
	{Name = "#20", Hash = 'FM_Tat_Award_F_018', Value = "multiplayer_overlays"},
	{Name = "#21", Hash = 'FM_Tat_Award_F_019', Value = "multiplayer_overlays"},
	{Name = "#22", Hash = 'FM_Tat_F_009', Value = "multiplayer_overlays"},
	{Name = "#23", Hash = 'FM_Tat_F_011', Value = "multiplayer_overlays"},
	{Name = "#24", Hash = 'FM_Tat_F_013', Value = "multiplayer_overlays"},
	{Name = "#25", Hash = 'FM_Tat_F_016', Value = "multiplayer_overlays"},
	{Name = "#26", Hash = 'FM_Tat_F_019', Value = "multiplayer_overlays"},
	{Name = "#23", Hash = 'FM_Tat_F_020', Value = "multiplayer_overlays"},
	{Name = "#24", Hash = 'FM_Tat_F_030', Value = "multiplayer_overlays"},
	{Name = "#25", Hash = 'FM_Tat_F_045', Value = "multiplayer_overlays"},
	{Name = "#26", Hash = 'FM_Tat_F_046', Value = "multiplayer_overlays"},
	{Name = "#27", Hash = 'FM_Tat_Award_F_000', Value = "multiplayer_overlays"},
	{Name = "#28", Hash = 'FM_Tat_Award_F_010', Value = "multiplayer_overlays"},
	{Name = "#29", Hash = 'FM_Tat_F_001', Value = "multiplayer_overlays"},
	{Name = "#30", Hash = 'FM_Tat_F_003', Value = "multiplayer_overlays"},
	{Name = "#31", Hash = 'FM_Tat_F_014', Value = "multiplayer_overlays"},
	{Name = "#32", Hash = 'FM_Tat_F_018', Value = "multiplayer_overlays"},
	{Name = "#33", Hash = 'FM_Tat_F_027', Value = "multiplayer_overlays"},
	{Name = "#34", Hash = 'FM_Tat_F_028', Value = "multiplayer_overlays"},
	{Name = "#35", Hash = 'FM_Tat_F_038', Value = "multiplayer_overlays"},
	{Name = "#36", Hash = 'FM_Tat_F_047', Value = "multiplayer_overlays"},
	{Name = "#37", Hash = 'FM_Tat_Award_F_002', Value = "multiplayer_overlays"},
	{Name = "#38", Hash = 'FM_Tat_M_000', Value = "multiplayer_overlays"},
	{Name = "#39", Hash = 'FM_Tat_Award_F_001', Value = "multiplayer_overlays"},
	{Name = "#40", Hash = 'FM_Tat_Award_F_007', Value = "multiplayer_overlays"},
	{Name = "#41", Hash = 'FM_Tat_Award_F_015', Value = "multiplayer_overlays"},
	{Name = "#45", Hash = 'FM_Tat_F_005', Value = "multiplayer_overlays"},
	{Name = "#46", Hash = 'FM_Tat_F_006', Value = "multiplayer_overlays"},
	{Name = "#47", Hash = 'FM_Tat_F_015', Value = "multiplayer_overlays"},
	{Name = "#48", Hash = 'FM_Tat_F_031', Value = "multiplayer_overlays"},
	{Name = "#49", Hash = 'FM_Tat_F_041', Value = "multiplayer_overlays"},
	{Name = "#50", Hash = 'FM_Tat_Award_F_006', Value = "multiplayer_overlays"},
	{Name = "#51", Hash = 'FM_Tat_F_007', Value = "multiplayer_overlays"},
	{Name = "#52", Hash = 'FM_Tat_F_017', Value = "multiplayer_overlays"},
	{Name = "#53", Hash = 'FM_Tat_F_022', Value = "multiplayer_overlays"},
	{Name = "#54", Hash = 'FM_Tat_F_039', Value = "multiplayer_overlays"},
	{Name = "#55", Hash = 'FM_Tat_F_040', Value = "multiplayer_overlays"},
	{Name = "#56", Hash = 'FM_Tat_F_042', Value = "multiplayer_overlays"},
	{Name = "#57", Hash = 'FM_Tat_F_043', Value = "multiplayer_overlays"},
	{Name = "#58", Hash = 'FM_Tat_Award_F_009', Value = "multiplayer_overlays"},
	{Name = "#59", Hash = 'FM_Tat_F_002', Value = "multiplayer_overlays"},
	{Name = "#60", Hash = 'FM_Tat_F_008', Value = "multiplayer_overlays"},
	{Name = "#61", Hash = 'FM_Tat_F_021', Value = "multiplayer_overlays"},
	{Name = "#62", Hash = 'FM_Tat_F_023', Value = "multiplayer_overlays"},
	{Name = "#63", Hash = 'FM_Tat_F_026', Value = "multiplayer_overlays"},
	{Name = "#64", Hash = 'FM_Tat_F_032', Value = "multiplayer_overlays"},
	{Name = "#65", Hash = 'FM_Tat_F_033', Value = "multiplayer_overlays"},
	{Name = "#66", Hash = 'FM_Tat_F_035', Value = "multiplayer_overlays"},
	{Name = "#67", Hash = 'FM_Tat_F_037', Value = "multiplayer_overlays"},
}

Config.NoelTatooList = {
	{Name = "#1", Hash = 'MP_Xmas2_F_Tat_009', Value = "mpchristmas2_overlays"},
	{Name = "#2", Hash = 'MP_Xmas2_F_Tat_013', Value = "mpchristmas2_overlays"},
	{Name = "#3", Hash = 'MP_Xmas2_F_Tat_016', Value = "mpchristmas2_overlays"},
	{Name = "#4", Hash = 'MP_Xmas2_F_Tat_017', Value = "mpchristmas2_overlays"},
	{Name = "#5", Hash = 'MP_Xmas2_F_Tat_018', Value = "mpchristmas2_overlays"},
	{Name = "#6", Hash = 'MP_Xmas2_F_Tat_019', Value = "mpchristmas2_overlays"},
	{Name = "#7", Hash = 'MP_Xmas2_F_Tat_028', Value = "mpchristmas2_overlays"},
	{Name = "#8", Hash = 'MP_Xmas2_F_Tat_005', Value = "mpchristmas2_overlays"},
	{Name = "#9", Hash = 'MP_Xmas2_F_Tat_006', Value = "mpchristmas2_overlays"},
	{Name = "#10", Hash = 'MP_Xmas2_F_Tat_011', Value = "mpchristmas2_overlays"},
	{Name = "#11", Hash = 'MP_Xmas2_F_Tat_015', Value = "mpchristmas2_overlays"},
	{Name = "#12", Hash = 'MP_Xmas2_F_Tat_003', Value = "mpchristmas2_overlays"},
	{Name = "#13", Hash = 'MP_Xmas2_F_Tat_004', Value = "mpchristmas2_overlays"},
	{Name = "#14", Hash = 'MP_Xmas2_F_Tat_008', Value = "mpchristmas2_overlays"},
	{Name = "#15", Hash = 'MP_Xmas2_F_Tat_022', Value = "mpchristmas2_overlays"},
	{Name = "#16", Hash = 'MP_Xmas2_F_Tat_023', Value = "mpchristmas2_overlays"},
	{Name = "#17", Hash = 'MP_Xmas2_F_Tat_026', Value = "mpchristmas2_overlays"},
	{Name = "#18", Hash = 'MP_Xmas2_F_Tat_027', Value = "mpchristmas2_overlays"},
	{Name = "#19", Hash = 'MP_Xmas2_F_Tat_000', Value = "mpchristmas2_overlays"},
	{Name = "#20", Hash = 'MP_Xmas2_F_Tat_010', Value = "mpchristmas2_overlays"},
	{Name = "#21", Hash = 'MP_Xmas2_F_Tat_020', Value = "mpchristmas2_overlays"},
	{Name = "#22", Hash = 'MP_Xmas2_F_Tat_021', Value = "mpchristmas2_overlays"},
	{Name = "#23", Hash = 'MP_Xmas2_F_Tat_014', Value = "mpchristmas2_overlays"},
	{Name = "#24", Hash = 'MP_Xmas2_F_Tat_001', Value = "mpchristmas2_overlays"},
	{Name = "#25", Hash = 'MP_Xmas2_F_Tat_002', Value = "mpchristmas2_overlays"},
}

Config.LuxeTatooList = {
	{Name = "#1", Hash = 'MP_LUXE_TAT_003_F', Value = "mpluxe_overlays"},
	{Name = "#2", Hash = 'MP_LUXE_TAT_008_F', Value = "mpluxe_overlays"},
	{Name = "#3", Hash = 'MP_LUXE_TAT_014_F', Value = "mpluxe_overlays"},
	{Name = "#4", Hash = 'MP_LUXE_TAT_015_F', Value = "mpluxe_overlays"},
	{Name = "#5", Hash = 'MP_LUXE_TAT_006_F', Value = "mpluxe_overlays"},
	{Name = "#6", Hash = 'MP_LUXE_TAT_024_F', Value = "mpluxe_overlays"},
	{Name = "#7", Hash = 'MP_LUXE_TAT_004_F', Value = "mpluxe_overlays"},
	{Name = "#8", Hash = 'MP_LUXE_TAT_013_F', Value = "mpluxe_overlays"},
	{Name = "#9", Hash = 'MP_LUXE_TAT_019_F', Value = "mpluxe_overlays"},
	{Name = "#10", Hash = 'MP_LUXE_TAT_009_F', Value = "mpluxe_overlays"},
	{Name = "#11", Hash = 'MP_LUXE_TAT_020_F', Value = "mpluxe_overlays"},
	{Name = "#12", Hash = 'MP_LUXE_TAT_001_F', Value = "mpluxe_overlays"},
	{Name = "#13", Hash = 'MP_LUXE_TAT_000_F', Value = "mpluxe_overlays"},
	{Name = "#14", Hash = 'MP_Luxe_Tat_012_F', Value = "mpluxe2_overlays"},
	{Name = "#15", Hash = 'MP_Luxe_Tat_025_F', Value = "mpluxe2_overlays"},
	{Name = "#16", Hash = 'MP_Luxe_Tat_027_F', Value = "mpluxe2_overlays"},
	{Name = "#17", Hash = 'MP_Luxe_Tat_002_F', Value = "mpluxe2_overlays"},
	{Name = "#18", Hash = 'MP_Luxe_Tat_010_F', Value = "mpluxe2_overlays"},
	{Name = "#19", Hash = 'MP_Luxe_Tat_017_F', Value = "mpluxe2_overlays"},
	{Name = "#20", Hash = 'MP_Luxe_Tat_026_F', Value = "mpluxe2_overlays"},
	{Name = "#21", Hash = 'MP_Luxe_Tat_030_F', Value = "mpluxe2_overlays"},
	{Name = "#22", Hash = 'MP_LUXE_TAT_005_F', Value = "mpluxe2_overlays"},
	{Name = "#23", Hash = 'MP_LUXE_TAT_016_F', Value = "mpluxe2_overlays"},
	{Name = "#24", Hash = 'MP_LUXE_TAT_018_F', Value = "mpluxe2_overlays"},
	{Name = "#25", Hash = 'MP_LUXE_TAT_028_F', Value = "mpluxe2_overlays"},
	{Name = "#26", Hash = 'MP_LUXE_TAT_031_F', Value = "mpluxe2_overlays"},
	{Name = "#27", Hash = 'MP_LUXE_TAT_023_F', Value = "mpluxe2_overlays"},
	{Name = "#28", Hash = 'MP_LUXE_TAT_011_F', Value = "mpluxe2_overlays"},
}

Config.LowRiderTatooList = {
	{Name = "#1", Hash = 'MP_LR_Tat_000_F', Value = "mplowrider2_overlays"},
	{Name = "#2", Hash = 'MP_LR_Tat_008_F', Value = "mplowrider2_overlays"},
	{Name = "#3", Hash = 'MP_LR_Tat_011_F', Value = "mplowrider2_overlays"},
	{Name = "#4", Hash = 'MP_LR_Tat_012_F', Value = "mplowrider2_overlays"},
	{Name = "#5", Hash = 'MP_LR_Tat_016_F', Value = "mplowrider2_overlays"},
	{Name = "#6", Hash = 'MP_LR_Tat_019_F', Value = "mplowrider2_overlays"},
	{Name = "#7", Hash = 'MP_LR_Tat_031_F', Value = "mplowrider2_overlays"},
	{Name = "#8", Hash = 'MP_LR_Tat_032_F', Value = "mplowrider2_overlays"},
	{Name = "#9", Hash = 'MP_LR_Tat_003_F', Value = "mplowrider2_overlays"},
	{Name = "#10", Hash = 'MP_LR_Tat_028_F', Value = "mplowrider2_overlays"},
	{Name = "#11", Hash = 'MP_LR_Tat_035_F', Value = "mplowrider2_overlays"},
	{Name = "#12", Hash = 'MP_LR_Tat_006_F', Value = "mplowrider2_overlays"},
	{Name = "#13", Hash = 'MP_LR_Tat_018_F', Value = "mplowrider2_overlays"},
	{Name = "#14", Hash = 'MP_LR_Tat_030_F', Value = "mplowrider2_overlays"},
	{Name = "#15", Hash = 'MP_LR_Tat_029_F', Value = "mplowrider2_overlays"},
}

Config.StuntTatooList = {
	{Name = "#1", Hash = 'MP_MP_Stunt_tat_011_F', Value = "mpstunt_overlays"},
	{Name = "#2", Hash = 'MP_MP_Stunt_tat_012_F', Value = "mpstunt_overlays"},
	{Name = "#3", Hash = 'MP_MP_Stunt_tat_014_F', Value = "mpstunt_overlays"},
	{Name = "#4", Hash = 'MP_MP_Stunt_tat_018_F', Value = "mpstunt_overlays"},
	{Name = "#5", Hash = 'MP_MP_Stunt_tat_019_F', Value = "mpstunt_overlays"},
	{Name = "#6", Hash = 'MP_MP_Stunt_tat_024_F', Value = "mpstunt_overlays"},
	{Name = "#7", Hash = 'MP_MP_Stunt_tat_026_F', Value = "mpstunt_overlays"},
	{Name = "#8", Hash = 'MP_MP_Stunt_tat_027_F', Value = "mpstunt_overlays"},
	{Name = "#9", Hash = 'MP_MP_Stunt_tat_029_F', Value = "mpstunt_overlays"},
	{Name = "#10", Hash = 'MP_MP_Stunt_tat_030_F', Value = "mpstunt_overlays"},
	{Name = "#11", Hash = 'MP_MP_Stunt_tat_033_F', Value = "mpstunt_overlays"},
	{Name = "#12", Hash = 'MP_MP_Stunt_tat_034_F', Value = "mpstunt_overlays"},
	{Name = "#13", Hash = 'MP_MP_Stunt_tat_037_F', Value = "mpstunt_overlays"},
	{Name = "#14", Hash = 'MP_MP_Stunt_tat_040_F', Value = "mpstunt_overlays"},
	{Name = "#15", Hash = 'MP_MP_Stunt_tat_041_F', Value = "mpstunt_overlays"},
	{Name = "#16", Hash = 'MP_MP_Stunt_tat_044_F', Value = "mpstunt_overlays"},
	{Name = "#17", Hash = 'MP_MP_Stunt_tat_046_F', Value = "mpstunt_overlays"},
	{Name = "#18", Hash = 'MP_MP_Stunt_tat_048_F', Value = "mpstunt_overlays"},
	{Name = "#19", Hash = 'MP_MP_Stunt_tat_003_F', Value = "mpstunt_overlays"},
	{Name = "#20", Hash = 'MP_MP_Stunt_tat_009_F', Value = "mpstunt_overlays"},
	{Name = "#21", Hash = 'MP_MP_Stunt_tat_010_F', Value = "mpstunt_overlays"},
	{Name = "#22", Hash = 'MP_MP_Stunt_tat_016_F', Value = "mpstunt_overlays"},
	{Name = "#23", Hash = 'MP_MP_Stunt_tat_036_F', Value = "mpstunt_overlays"},
	{Name = "#24", Hash = 'MP_MP_Stunt_tat_038_F', Value = "mpstunt_overlays"},
	{Name = "#25", Hash = 'MP_MP_Stunt_tat_049_F', Value = "mpstunt_overlays"},
	{Name = "#26", Hash = 'MP_MP_Stunt_tat_001_F', Value = "mpstunt_overlays"},
	{Name = "#27", Hash = 'MP_MP_Stunt_tat_002_F', Value = "mpstunt_overlays"},
	{Name = "#28", Hash = 'MP_MP_Stunt_tat_008_F', Value = "mpstunt_overlays"},
	{Name = "#29", Hash = 'MP_MP_Stunt_tat_022_F', Value = "mpstunt_overlays"},
	{Name = "#30", Hash = 'MP_MP_Stunt_tat_023_F', Value = "mpstunt_overlays"},
	{Name = "#31", Hash = 'MP_MP_Stunt_tat_035_F', Value = "mpstunt_overlays"},
	{Name = "#32", Hash = 'MP_MP_Stunt_tat_039_F', Value = "mpstunt_overlays"},
	{Name = "#33", Hash = 'MP_MP_Stunt_tat_043_F', Value = "mpstunt_overlays"},
	{Name = "#34", Hash = 'MP_MP_Stunt_tat_005_F', Value = "mpstunt_overlays"},
	{Name = "#35", Hash = 'MP_MP_Stunt_tat_015_F', Value = "mpstunt_overlays"},
	{Name = "#36", Hash = 'MP_MP_Stunt_tat_020_F', Value = "mpstunt_overlays"},
	{Name = "#37", Hash = 'MP_MP_Stunt_tat_025_F', Value = "mpstunt_overlays"},
	{Name = "#38", Hash = 'MP_MP_Stunt_tat_032_F', Value = "mpstunt_overlays"},
	{Name = "#39", Hash = 'MP_MP_Stunt_tat_045_F', Value = "mpstunt_overlays"},
	{Name = "#40", Hash = 'MP_MP_Stunt_tat_047_F', Value = "mpstunt_overlays"},
	{Name = "#41", Hash = 'MP_MP_Stunt_tat_007_F', Value = "mpstunt_overlays"},
	{Name = "#42", Hash = 'MP_MP_Stunt_tat_013_F', Value = "mpstunt_overlays"},
	{Name = "#43", Hash = 'MP_MP_Stunt_tat_021_F', Value = "mpstunt_overlays"},
	{Name = "#44", Hash = 'MP_MP_Stunt_tat_028_F', Value = "mpstunt_overlays"},
	{Name = "#45", Hash = 'MP_MP_Stunt_tat_031_F', Value = "mpstunt_overlays"},
}

Config.BikerTatooList = {
	{Name = "#1", Hash = 'MP_MP_Biker_Tat_000_F', Value = "mpbiker_overlays"},
	{Name = "#2", Hash = 'MP_MP_Biker_Tat_001_F', Value = "mpbiker_overlays"},
	{Name = "#3", Hash = 'MP_MP_Biker_Tat_003_F', Value = "mpbiker_overlays"},
	{Name = "#4", Hash = 'MP_MP_Biker_Tat_005_F', Value = "mpbiker_overlays"},
	{Name = "#5", Hash = 'MP_MP_Biker_Tat_006_F', Value = "mpbiker_overlays"},
	{Name = "#6", Hash = 'MP_MP_Biker_Tat_008_F', Value = "mpbiker_overlays"},
	{Name = "#7", Hash = 'MP_MP_Biker_Tat_010_F', Value = "mpbiker_overlays"},
	{Name = "#8", Hash = 'MP_MP_Biker_Tat_011_F', Value = "mpbiker_overlays"},
	{Name = "#9", Hash = 'MP_MP_Biker_Tat_013_F', Value = "mpbiker_overlays"},
	{Name = "#10", Hash = 'MP_MP_Biker_Tat_017_F', Value = "mpbiker_overlays"},
	{Name = "#11", Hash = 'MP_MP_Biker_Tat_018_F', Value = "mpbiker_overlays"},
	{Name = "#12", Hash = 'MP_MP_Biker_Tat_019_F', Value = "mpbiker_overlays"},
	{Name = "#13", Hash = 'MP_MP_Biker_Tat_021_F', Value = "mpbiker_overlays"},
	{Name = "#14", Hash = 'MP_MP_Biker_Tat_023_F', Value = "mpbiker_overlays"},
	{Name = "#15", Hash = 'MP_MP_Biker_Tat_026_F', Value = "mpbiker_overlays"},
	{Name = "#16", Hash = 'MP_MP_Biker_Tat_029_F', Value = "mpbiker_overlays"},
	{Name = "#17", Hash = 'MP_MP_Biker_Tat_030_F', Value = "mpbiker_overlays"},
	{Name = "#18", Hash = 'MP_MP_Biker_Tat_031_F', Value = "mpbiker_overlays"},
	{Name = "#19", Hash = 'MP_MP_Biker_Tat_032_F', Value = "mpbiker_overlays"},
	{Name = "#20", Hash = 'MP_MP_Biker_Tat_034_F', Value = "mpbiker_overlays"},
	{Name = "#21", Hash = 'MP_MP_Biker_Tat_039_F', Value = "mpbiker_overlays"},
	{Name = "#22", Hash = 'MP_MP_Biker_Tat_041_F', Value = "mpbiker_overlays"},
	{Name = "#23", Hash = 'MP_MP_Biker_Tat_043_F', Value = "mpbiker_overlays"},
	{Name = "#24", Hash = 'MP_MP_Stunt_tat_050_F', Value = "mpbiker_overlays"},
	{Name = "#25", Hash = 'MP_MP_Stunt_tat_052_F', Value = "mpbiker_overlays"},
	{Name = "#26", Hash = 'MP_MP_Stunt_tat_058_F', Value = "mpbiker_overlays"},
	{Name = "#27", Hash = 'MP_MP_Stunt_tat_059_F', Value = "mpbiker_overlays"},
	{Name = "#28", Hash = 'MP_MP_Stunt_tat_060_F', Value = "mpbiker_overlays"},
	{Name = "#29", Hash = 'MP_MP_Biker_Tat_007_F', Value = "mpbiker_overlays"},
	{Name = "#30", Hash = 'MP_MP_Biker_Tat_014_F', Value = "mpbiker_overlays"},
	{Name = "#31", Hash = 'MP_MP_Biker_Tat_033_F', Value = "mpbiker_overlays"},
	{Name = "#32", Hash = 'MP_MP_Biker_Tat_042_F', Value = "mpbiker_overlays"},
	{Name = "#33", Hash = 'MP_MP_Biker_Tat_046_F', Value = "mpbiker_overlays"},
	{Name = "#34", Hash = 'MP_MP_Biker_Tat_047_F', Value = "mpbiker_overlays"},
	{Name = "#35", Hash = 'MP_MP_Biker_Tat_049_F', Value = "mpbiker_overlays"},
	{Name = "#36", Hash = 'MP_MP_Biker_Tat_054_F', Value = "mpbiker_overlays"},
	{Name = "#37", Hash = 'MP_MP_Biker_Tat_012_F', Value = "mpbiker_overlays"},
	{Name = "#38", Hash = 'MP_MP_Biker_Tat_016_F', Value = "mpbiker_overlays"},
	{Name = "#39", Hash = 'MP_MP_Biker_Tat_020_F', Value = "mpbiker_overlays"},
	{Name = "#40", Hash = 'MP_MP_Biker_Tat_024_F', Value = "mpbiker_overlays"},
	{Name = "#41", Hash = 'MP_MP_Biker_Tat_025_F', Value = "mpbiker_overlays"},
	{Name = "#42", Hash = 'MP_MP_Biker_Tat_035_F', Value = "mpbiker_overlays"},
	{Name = "#43", Hash = 'MP_MP_Biker_Tat_045_F', Value = "mpbiker_overlays"},
	{Name = "#44", Hash = 'MP_MP_Biker_Tat_053_F', Value = "mpbiker_overlays"},
	{Name = "#45", Hash = 'MP_MP_Biker_Tat_055_F', Value = "mpbiker_overlays"},
	{Name = "#46", Hash = 'MP_MP_Biker_Tat_004_F', Value = "mpbiker_overlays"},
	{Name = "#47", Hash = 'MP_MP_Biker_Tat_022_F', Value = "mpbiker_overlays"},
	{Name = "#48", Hash = 'MP_MP_Biker_Tat_028_F', Value = "mpbiker_overlays"},
	{Name = "#49", Hash = 'MP_MP_Biker_Tat_040_F', Value = "mpbiker_overlays"},
	{Name = "#50", Hash = 'MP_MP_Biker_Tat_048_F', Value = "mpbiker_overlays"},
	{Name = "#51", Hash = 'MP_MP_Biker_Tat_002_F', Value = "mpbiker_overlays"},
	{Name = "#52", Hash = 'MP_MP_Biker_Tat_015_F', Value = "mpbiker_overlays"},
	{Name = "#53", Hash = 'MP_MP_Biker_Tat_027_F', Value = "mpbiker_overlays"},
	{Name = "#54", Hash = 'MP_MP_Biker_Tat_036_F', Value = "mpbiker_overlays"},
	{Name = "#55", Hash = 'MP_MP_Biker_Tat_037_F', Value = "mpbiker_overlays"},
	{Name = "#56", Hash = 'MP_MP_Biker_Tat_044_F', Value = "mpbiker_overlays"},
	{Name = "#57", Hash = 'MP_MP_Biker_Tat_056_F', Value = "mpbiker_overlays"},
	{Name = "#58", Hash = 'MP_MP_Biker_Tat_057_F', Value = "mpbiker_overlays"},
}

Config.ExportTatooList = {
	{Name = "#1", Hash = 'MP_MP_ImportExport_Tat_000_F', Value = "mpimportexport_overlays"},
	{Name = "#2", Hash = 'MP_MP_ImportExport_Tat_001_F', Value = "mpimportexport_overlays"},
	{Name = "#3", Hash = 'MP_MP_ImportExport_Tat_002_F', Value = "mpimportexport_overlays"},
	{Name = "#4", Hash = 'MP_MP_ImportExport_Tat_009_F', Value = "mpimportexport_overlays"},
	{Name = "#5", Hash = 'MP_MP_ImportExport_Tat_010_F', Value = "mpimportexport_overlays"},
	{Name = "#6", Hash = 'MP_MP_ImportExport_Tat_011_F', Value = "mpimportexport_overlays"},
	{Name = "#7", Hash = 'MP_MP_ImportExport_Tat_003_F', Value = "mpimportexport_overlays"},
	{Name = "#8", Hash = 'MP_MP_ImportExport_Tat_005_F', Value = "mpimportexport_overlays"},
	{Name = "#9", Hash = 'MP_MP_ImportExport_Tat_006_F', Value = "mpimportexport_overlays"},
	{Name = "#10", Hash = 'MP_MP_ImportExport_Tat_007_F', Value = "mpimportexport_overlays"},
	{Name = "#11", Hash = 'MP_MP_ImportExport_Tat_004_F', Value = "mpimportexport_overlays"},
	{Name = "#12", Hash = 'MP_MP_ImportExport_Tat_008_F', Value = "mpimportexport_overlays"},
}

Config.GunTatooList = {
	{Name = "#1", Hash = 'MP_Gunrunning_Tattoo_000_F', Value = "mpgunrunning_overlays"},
	{Name = "#2", Hash = 'MP_Gunrunning_Tattoo_001_F', Value = "mpgunrunning_overlays"},
	{Name = "#3", Hash = 'MP_Gunrunning_Tattoo_009_F', Value = "mpgunrunning_overlays"},
	{Name = "#4", Hash = 'MP_Gunrunning_Tattoo_010_F', Value = "mpgunrunning_overlays"},
	{Name = "#5", Hash = 'MP_Gunrunning_Tattoo_012_F', Value = "mpgunrunning_overlays"},
	{Name = "#6", Hash = 'MP_Gunrunning_Tattoo_013_F', Value = "mpgunrunning_overlays"},
	{Name = "#7", Hash = 'MP_Gunrunning_Tattoo_014_F', Value = "mpgunrunning_overlays"},
	{Name = "#8", Hash = 'MP_Gunrunning_Tattoo_017_F', Value = "mpgunrunning_overlays"},
	{Name = "#9", Hash = 'MP_Gunrunning_Tattoo_018_F', Value = "mpgunrunning_overlays"},
	{Name = "#10", Hash = 'MP_Gunrunning_Tattoo_019_F', Value = "mpgunrunning_overlays"},
	{Name = "#11", Hash = 'MP_Gunrunning_Tattoo_020_F', Value = "mpgunrunning_overlays"},
	{Name = "#12", Hash = 'MP_Gunrunning_Tattoo_022_F', Value = "mpgunrunning_overlays"},
	{Name = "#13", Hash = 'MP_Gunrunning_Tattoo_028_F', Value = "mpgunrunning_overlays"},
	{Name = "#14", Hash = 'MP_Gunrunning_Tattoo_029_F', Value = "mpgunrunning_overlays"},
	{Name = "#15", Hash = 'MP_Gunrunning_Tattoo_003_F', Value = "mpgunrunning_overlays"},
	{Name = "#16", Hash = 'MP_Gunrunning_Tattoo_002_F', Value = "mpgunrunning_overlays"},
	{Name = "#17", Hash = 'MP_Gunrunning_Tattoo_021_F', Value = "mpgunrunning_overlays"},
	{Name = "#18", Hash = 'MP_Gunrunning_Tattoo_024_F', Value = "mpgunrunning_overlays"},
	{Name = "#19", Hash = 'MP_Gunrunning_Tattoo_004_F', Value = "mpgunrunning_overlays"},
	{Name = "#20", Hash = 'MP_Gunrunning_Tattoo_008_F', Value = "mpgunrunning_overlays"},
	{Name = "#21", Hash = 'MP_Gunrunning_Tattoo_015_F', Value = "mpgunrunning_overlays"},
	{Name = "#22", Hash = 'MP_Gunrunning_Tattoo_016_F', Value = "mpgunrunning_overlays"},
	{Name = "#23", Hash = 'MP_Gunrunning_Tattoo_025_F', Value = "mpgunrunning_overlays"},
	{Name = "#24", Hash = 'MP_Gunrunning_Tattoo_027_F', Value = "mpgunrunning_overlays"},
	{Name = "#25", Hash = 'MP_Gunrunning_Tattoo_006_F', Value = "mpgunrunning_overlays"},
	{Name = "#26", Hash = 'MP_Gunrunning_Tattoo_026_F', Value = "mpgunrunning_overlays"},
	{Name = "#27", Hash = 'MP_Gunrunning_Tattoo_030_F', Value = "mpgunrunning_overlays"},
	{Name = "#28", Hash = 'MP_Gunrunning_Tattoo_005_F', Value = "mpgunrunning_overlays"},
	{Name = "#29", Hash = 'MP_Gunrunning_Tattoo_007_F', Value = "mpgunrunning_overlays"},
	{Name = "#30", Hash = 'MP_Gunrunning_Tattoo_011_F', Value = "mpgunrunning_overlays"},
	{Name = "#31", Hash = 'MP_Gunrunning_Tattoo_023_F', Value = "mpgunrunning_overlays"},
}