Wheels = {
    Found = {},
    Smoke = {
        {Value = {255, 255, 255}, Name = "Blanc"},
        {Value = {255, 0, 0}, Name = "Rouge"},
        {Value = {255, 150, 0}, Name = "Orange"},
        {Value = {255, 255, 0}, Name = "Jaune"},
        {Value = {150, 255, 0}, Name = "Vert rally"},
        {Value = {0, 255, 0}, Name = "Vert"},
        {Value = {0, 255, 150}, Name = "Turquoise"},
        {Value = {0, 255, 150}, Name = "Bleu rally"},
        {Value = {0, 0, 255}, Name = "Bleu"},
        {Value = {150, 0, 255}, Name = "Mauve"},
        {Value = {255, 0, 255}, Name = "Rose"},
    },
    ["Sport"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Inferno"},
        {Value = 1, Name = "Deepfive"},
        {Value = 2, Name = "Lozspeed"},
        {Value = 3, Name = "Diamondcut"},
        {Value = 4, Name = "Chrono"},
        {Value = 5, Name = "Ferocirr"},
        {Value = 6, Name = "Fiftynine"},
        {Value = 7, Name = "Mercie"},
        {Value = 8, Name = "Synthéticz"},
        {Value = 9, Name = "Organictyped"},
        {Value = 10, Name = "Endov1"},
        {Value = 11, Name = "Duper7"},
        {Value = 12, Name = "Uzer"},
        {Value = 13, Name = "Groundride"},
        {Value = 14, Name = "Spacer"},
        {Value = 15, Name = "Venum"},
        {Value = 16, Name = "Cosmo"},
        {Value = 17, Name = "Dashvip"},
        {Value = 18, Name = "Icekid"},
        {Value = 19, Name = "Ruffled"},
        {Value = 20, Name = "Wangermaster"},
        {Value = 21, Name = "Superfive"},
        {Value = 22, Name = "Endov2"},
        {Value = 23, Name = "Slitix"},
    },
    ["Suv"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Vip"},
        {Value = 1, Name = "Benefactor"},
        {Value = 2, Name = "Cosmo"},
        {Value = 3, Name = "Bippu"},
        {Value = 4, Name = "Royalsix"},
        {Value = 5, Name = "Fagorm"},
        {Value = 6, Name = "Deluxe"},
        {Value = 7, Name = "Icedout"},
        {Value = 8, Name = "Cognscenti"},
        {Value = 9, Name = "Lozspeedten"},
        {Value = 10, Name = "Supernova"},
        {Value = 11, Name = "Obeyrs"},
        {Value = 12, Name = "Lozspeedballer"},
        {Value = 13, Name = "Extra vaganzo"},
        {Value = 14, Name = "Splitix"},
        {Value = 15, Name = "Empowered"},
        {Value = 16, Name = "Sunrize"},
        {Value = 17, Name = "Dashvip"},
        {Value = 18, Name = "Cutter"},
    },
    ["Offroad"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Raider"},
        {Value = 1, Name = "Mudslinger"},
        {Value = 2, Name = "Nevis"},
        {Value = 3, Name = "Cairngorm"},
        {Value = 4, Name = "Amazon"},
        {Value = 5, Name = "Challenger"},
        {Value = 6, Name = "Dunebasher"},
        {Value = 7, Name = "Fivestar"},
        {Value = 8, Name = "Rockcrawler"},
        {Value = 9, Name = "Milspecsteelie"},
    },
    ["Tuning"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Cosmo"},
        {Value = 1, Name = "Supermesh"},
        {Value = 2, Name = "Outsider"},
        {Value = 3, Name = "Rollas"},
        {Value = 4, Name = "Driffmeister"},
        {Value = 5, Name = "Slicer"},
        {Value = 6, Name = "Elquatro"},
        {Value = 7, Name = "Dubbed"},
        {Value = 8, Name = "Fivestar"},
        {Value = 9, Name = "Slideways"},
        {Value = 10, Name = "Apex"},
        {Value = 11, Name = "Stancedeg"},
        {Value = 12, Name = "Countersteer"},
        {Value = 13, Name = "Endov1"},
        {Value = 14, Name = "Endov2dish"},
        {Value = 15, Name = "Guppez"},
        {Value = 16, Name = "Chokadori"},
        {Value = 17, Name = "Chicane"},
        {Value = 18, Name = "Saisoku"},
        {Value = 19, Name = "Dishedeight"},
        {Value = 20, Name = "Fujiwara"},
        {Value = 21, Name = "Zokusha"},
        {Value = 22, Name = "Battlevill"},
        {Value = 23, Name = "Rallymaster"},
    },
    ["Luxe"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Shadow"},
        {Value = 1, Name = "Hyper"},
        {Value = 2, Name = "Blade"},
        {Value = 3, Name = "Diamond"},
        {Value = 4, Name = "Supagee"},
        {Value = 5, Name = "Chromaticz"},
        {Value = 6, Name = "Merciechilp"},
        {Value = 7, Name = "Obeyrs"},
        {Value = 8, Name = "GtChrome"},
        {Value = 9, Name = "Cheetahr"},
        {Value = 10, Name = "Solar"},
        {Value = 11, Name = "Splitten"},
        {Value = 12, Name = "Dashvip"},
        {Value = 13, Name = "Lozspeedten"},
        {Value = 14, Name = "Carboninferno"},
        {Value = 15, Name = "Carbonshadow"},
        {Value = 16, Name = "Carbonz"},
        {Value = 17, Name = "Carbonsolar"},
        {Value = 18, Name = "Carboncheetahr"},
        {Value = 19, Name = "Carbonsracer"},
    },
    ["Lowrider"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Flare"},
        {Value = 1, Name = "Wired"},
        {Value = 2, Name = "Triplegolds"},
        {Value = 3, Name = "Bigworm"},
        {Value = 4, Name = "Sevenfives"},
        {Value = 5, Name = "Splitsix"},
        {Value = 6, Name = "Freshmesh"},
        {Value = 7, Name = "Leadsled"},
        {Value = 8, Name = "Turbine"},
        {Value = 9, Name = "Superfin"},
        {Value = 10, Name = "Classicrod"},
        {Value = 11, Name = "Dollar"},
        {Value = 12, Name = "Dukes"},
        {Value = 13, Name = "Lowfive"},
        {Value = 14, Name = "Gooch"},
    },
    ["Muscle"] = {
        {Value = -1, Name = "Aucun"},
        {Value = 0, Name = "Classicfive"},
        {Value = 1, Name = "Dukes"},
        {Value = 2, Name = "Musclefreak"},
        {Value = 3, Name = "Kracka"},
        {Value = 4, Name = "Azrea"},
        {Value = 5, Name = "Mecha"},
        {Value = 6, Name = "Blacktop"},
        {Value = 7, Name = "Dragspl"},
        {Value = 8, Name = "Revolver"},
        {Value = 9, Name = "Classicrod"},
        {Value = 10, Name = "Spooner"},
        {Value = 11, Name = "Fivestar"},
        {Value = 12, Name = "Oldschool"},
        {Value = 13, Name = "Eljefe"},
        {Value = 14, Name = "Dodman"},
        {Value = 15, Name = "Sixgun"},
        {Value = 16, Name = "Mercenary"},
    },
}
Mods = {
    Perfs = {
        {Value = 11, Name = "Moteur", Table = 
            {
                {Name = "Level 1", Value = 0},
                {Name = "Level 2", Value = 1},
                {Name = "Level 3", Value = 2},
            },
        },
        {Value = 18, Name = "Turbo", Table = 
            {
                {Name = "Avec", Value = 0},
                {Name = "Sans", Value = 1},
            }
        },
        {Value = 13, Name = "Transmission", Table = 
            {
                {Name = "Level 1", Value = 0},
                {Name = "Level 2", Value = 1},
                {Name = "Level 3", Value = 2},
            }
        },
        {Value = 15, Name = "Suspension", Table = 
            {
                {Name = "Level 1", Value = 0},
                {Name = "Level 2", Value = 1},
                {Name = "Level 3", Value = 2},
                {Name = "Level 4", Value = 3},
            }
        },
        {Value = 12, Name = "Frein", Table = 
            {
                {Name = "Level 1", Value = 0},
                {Name = "Level 2", Value = 1},
                {Name = "Level 3", Value = 2},
            }
        },
    },
    Custom = {
        {Value = 48, Name = "Autocollants"},
        {Value = 46, Name = "Fenêtres"},
        {Value = 45, Name = "Réservoir"},
        {Value = 44, Name = "Prise d'air"},
        {Value = 43, Name = "Antenne"},
        {Value = 41, Name = "Entretoise"},
        {Value = 40, Name = "Flitre a air"},
        {Value = 39, Name = "Block moteur"},
        {Value = 38, Name = "Suspenssion hydraulique"},
        {Value = 37, Name = "Coffre"},
        {Value = 36, Name = "Haut parleurs"},
        {Value = 35, Name = "Plaques"},
        {Value = 34, Name = "Levier de vitesse"},
        {Value = 33, Name = "Volant"},
        {Value = 32, Name = "Sièges"},
        {Value = 31, Name = "Portières"},
        {Value = 30, Name = "Habitacle"},
        {Value = 29, Name = "Tableau de bord"},
        {Value = 28, Name = "Accessoires"},
        {Value = 27, Name = "Intèrieur"},
        {Value = 25, Name = "Support de plaque"},
        {Value = 10, Name = "Toît"},
        {Value = 8, Name = "Ailes"},
        {Value = 7, Name = "Capot"},
        {Value = 6, Name = "Grille"},
        {Value = 5, Name = "Arceau"},
        {Value = 4, Name = "Échappement"},
        {Value = 3, Name = "Bas de caisse"},
        {Value = 2, Name = "Pare chocs arrière"},
        {Value = 1, Name = "Pare chocs avant"},
        {Value = 0, Name = "Spoiler"},
    },
},
Windows = {
    Index = 1,
    Table = {
        {Value = false, Name = "Classique"},
        {Value = 1, Name = "Pure black"},
        {Value = 2, Name = "Fumée foncé"},
        {Value = 3, Name = "Fumée clair"},
        {Value = 4, Name = "Limousine"},
        {Value = 5, Name = "Vert"},
    },
},
Horn = {
    Index = 1,
    Table = {
        {Value = 0, Name = "Truck Horn"},
        {Value = 1, Name = "Cop Horn"},
        {Value = 2, Name = "Clown Horn"},
        {Value = 3, Name = "Musical Horn 1"},
        {Value = 4, Name = "Musical Horn 2"},
        {Value = 5, Name = "Musical Horn 3"},
        {Value = 6, Name = "Musical Horn 4"},
        {Value = 7, Name = "Musical Horn 5"},
        {Value = 8, Name = "Sad Trombone"},
        {Value = 9, Name = "Classical Horn 1"},
        {Value = 10, Name = "Classical Horn 2"},
        {Value = 11, Name = "Classical Horn 3"},
        {Value = 12, Name = "Classical Horn 4"},
        {Value = 13, Name = "Classical Horn 5"},
        {Value = 14, Name = "Classical Horn 6"},
        {Value = 15, Name = "Classical Horn 7"},
        {Value = 16, Name = "Scale - Do"},
        {Value = 17, Name = "Scale - Re"},
        {Value = 18, Name = "Scale - Mi"},
        {Value = 19, Name = "Scale - Fa"},
        {Value = 20, Name = "Scale - Sol"},
        {Value = 21, Name = "Scale - La"},
        {Value = 22, Name = "Scale - Ti"},
        {Value = 23, Name = "Scale - Do"},
        {Value = 24, Name = "Jazz Horn 1"},
        {Value = 25, Name = "Jazz Horn 2"},
        {Value = 26, Name = "Jazz Horn 3"},
        {Value = 27, Name = "Jazz Horn Loop"},
        {Value = 28, Name = "Star Spangled Banner 1"},
        {Value = 29, Name = "Star Spangled Banner 2"},
        {Value = 30, Name = "Star Spangled Banner 3"},
        {Value = 31, Name = "Star Spangled Banner 4"},
        {Value = 32, Name = "Classical Horn 8 Loop"},
        {Value = 33, Name = "Classical Horn 9 Loop"},
        {Value = 34, Name = "Classical Horn 10 Loop"},
        {Value = 35, Name = "Classical Horn 8"},
        {Value = 36, Name = "Classical Horn 9"},
        {Value = 37, Name = "Classical Horn 10"},
        {Value = 38, Name = "Funeral Loop"},
        {Value = 39, Name = "Funeral"},
        {Value = 40, Name = "Spooky Loop"},
        {Value = 41, Name = "Spooky"},
        {Value = 42, Name = "San Andreas Loop"},
        {Value = 43, Name = "San Andreas"},
        {Value = 44, Name = "Liberty City Loop"},
        {Value = 45, Name = "Liberty City"},
        {Value = 46, Name = "Festive 1 Loop"},
        {Value = 47, Name = "Festive 1"},
        {Value = 48, Name = "Festive 2 Loop"},
        {Value = 49, Name = "Festive 2"},
        {Value = 50, Name = "Festive 3 Loop"},
        {Value = 51, Name = "Festive 3"},
    },
},
Plate = {
    Index = 1,
    Table = {
        {Value = 0, Name = 'Bleu sur blanc'},
        {Value = 1, Name = 'Jaune sur noir'},
        {Value = 2, Name = 'Jaune sur bleu'},
        {Value = 3, Name = 'Bleu sur blanc 2'},
        {Value = 4, Name = 'Bleu sur blanc 3'},
    },
},
Headlight = {
    Index = 1,
    Table = {
        {Value = false, Name = 'Classique'},
        {Value = true, Name = 'Xenon'},
    },
},
Color = {
    Found = {},
    Table = {
        {Name = "Blanc", Value = 1},
        {Name = "Gris", Value = 2},
        {Name = "Noir", Value = 3},
        {Name = "Marron", Value = 4},
        {Name = "Rouge", Value = 5},
        {Name = "Rose", Value = 6},
        {Name = "Violet", Value = 7},
        {Name = "Jaune", Value = 8},
        {Name = "Orange", Value = 9},
        {Name = "Vert", Value = 10},
        {Name = "Bleu", Value = 11},
        {Name = "Chrome", Value = 12},
        {Name = "Or", Value = 13},
    },
    ["Blanc"] = {
        {Value = 106, Name = "Vanille"},
        {Value = 107, Name = "Crême"},
        {Value = 111, Name = "Blanc"},
        {Value = 112, Name = "Blanc polaire"},
        {Value = 113, Name = "Beige"},
        {Value = 121, Name = "Blacn mat"},
        {Value = 122, Name = "Neige"},
        {Value = 131, Name = "Cotton"},
        {Value = 132, Name = "Albâtre"},
        {Value = 134, Name = "Blanc pure"},
    },
    ["Gris"] = {
        {Value = 4, Name = "Gris"},
        {Value = 5, Name = "Argent"},
        {Value = 6, Name = "Gris métallisé"},
        {Value = 7, Name = "Acier laminé"},
        {Value = 8, Name = "Gris foncé"},
        {Value = 9, Name = "Gris rocheux"},
        {Value = 10, Name = "Gris nuit"},
        {Value = 13, Name = "Aluminium"},
        {Value = 14, Name = "Gris mat"},
        {Value = 17, Name = "Gris clair"},
        {Value = 18, Name = "Gris bitume"},
        {Value = 19, Name = "Gris béton"},
        {Value = 20, Name = "Argent sombre"},
        {Value = 22, Name = "Magnésite"},
        {Value = 23, Name = "Nickel"},
        {Value = 24, Name = "Zinc"},
        {Value = 25, Name = "Dolomite"},
        {Value = 26, Name = "Argent bleuté"},
        {Value = 66, Name = "Titane"},
        {Value = 93, Name = "Acier bleu"},
        {Value = 144, Name = "Champagne"},
        {Value = 156, Name = "Gris chasseur"},
    },
    ["Noir"] = {
        {Value = 0, Name = "Noir"},
        {Value = 1, Name = "Graphite"},
        {Value = 2, Name = "Noir métallisé"},
        {Value = 3, Name = "Noir acier"},
        {Value = 11, Name = "Anthracite"},
        {Value = 12, Name = "Noir mat"},
        {Value = 15, Name = "Nuit sombre"},
        {Value = 16, Name = "Noir profond"},
        {Value = 21, Name = "Pétrol"},
        {Value = 147, Name = "Carbon"},
    },
    ["Marron"] = {
        {Value = 45, Name = "Cuivre"},
        {Value = 47, Name = "Marron clair"},
        {Value = 48, Name = "Marron foncé"},
        {Value = 90, Name = "Bronze"},
        {Value = 94, Name = "Marron métallisé"},
        {Value = 95, Name = "Café"},
        {Value = 96, Name = "Terre cuite"},
        {Value = 97, Name = "Marbre"},
        {Value = 98, Name = "Sable"},
        {Value = 99, Name = "Sépia"},
        {Value = 100, Name = "Bison"},
        {Value = 101, Name = "Palmier"},
        {Value = 102, Name = "Caramel"},
        {Value = 103, Name = "Rouille"},
        {Value = 104, Name = "Chataigne"},
        {Value = 105, Name = "Noisette"},
        {Value = 108, Name = "Coquillage"},
        {Value = 109, Name = "Acajou"},
        {Value = 110, Name = "Chaudron"},
        {Value = 114, Name = "Blond"},
        {Value = 115, Name = "Gravier"},
        {Value = 116, Name = "Terre"},
    },
    ["Rouge"] = {
        {Value = 27, Name = "Rouge"},
        {Value = 28, Name = "Rouge turin"},
        {Value = 29, Name = "Coquelicot"},
        {Value = 30, Name = "Rouge cuivré"},
        {Value = 31, Name = "Rouge cardinal"},
        {Value = 32, Name = "Rouge brique"},
        {Value = 33, Name = "Grenat"},
        {Value = 34, Name = "Pourpre"},
        {Value = 35, Name = "Framboise"},
        {Value = 39, Name = "Rouge mat"},
        {Value = 40, Name = "Rouge foncé"},
        {Value = 43, Name = "Rouge pulpeux"},
        {Value = 44, Name = "Rouge brillant"},
        {Value = 46, Name = "Rouge pâle"},
        {Value = 143, Name = "Rouge vin"},
        {Value = 150, Name = "Rouge volcano"},
    },
    ["Rose"] = {
        {Value = 135, Name = "Rose"},
        {Value = 136, Name = "Saumon"},
        {Value = 137, Name = "Rose bonbon"},
    },
    ["Violet"] = {
        {Value = 71, Name = "Indigo"},
        {Value = 72, Name = "Violet profond"},
        {Value = 76, Name = "Violet foncé"},
        {Value = 81, Name = "Améthyste"},
        {Value = 142, Name = "Violet mystique"},
        {Value = 145, Name = "Saumon métallisé"},
        {Value = 148, Name = "Violet mat"},
        {Value = 149, Name = "Violet profond mat"},
    },
    ["Jaune"] = {
        {Value = 42, Name = "Jaune"},
        {Value = 88, Name = "Jaune blé"},
        {Value = 89, Name = "Jaune rally"},
        {Value = 91, Name = "Jaune clair"},
        {Value = 126, Name = "Jaune pâle"},
    },
    ["Orange"] = {
        {Value = 36, Name = "Orange"},
        {Value = 38, Name = "Tangerine"},
        {Value = 41, Name = "Orange mat"},
        {Value = 123, Name = "Orange clair"},
        {Value = 124, Name = "Pèche"},
        {Value = 130, Name = "Citrouille"},
        {Value = 138, Name = "Orange lamborghini"},
    },
    ["Vert"] = {
        {Value = 49, Name = "Vert foncé"},
        {Value = 50, Name = "Vert rally"},
        {Value = 51, Name = "Vert sapin"},
        {Value = 52, Name = "Vert olive"},
        {Value = 53, Name = "Vert clair"},
        {Value = 55, Name = "Vert lime"},
        {Value = 56, Name = "Vert forêt"},
        {Value = 57, Name = "Vert pelouse"},
        {Value = 58, Name = "Vert impérial"},
        {Value = 59, Name = "Vert bouteille"},
        {Value = 92, Name = "Vert citrus"},
        {Value = 125, Name = "Vert anis"},
        {Value = 128, Name = "Vert kaki"},
        {Value = 133, Name = "Vert army"},
        {Value = 151, Name = "Vert sombre"},
        {Value = 152, Name = "Vert chasseur"},
        {Value = 155, Name = "Amarylisse"},
    },
    ["Bleu"] = {
        {Value = 54, Name = "Topaze"},
        {Value = 60, Name = "Bleu clair"},
        {Value = 61, Name = "Bleu galaxy"},
        {Value = 63, Name = "Bleu foncé"},
        {Value = 64, Name = "Bleu azur"},
        {Value = 65, Name = "Bleu marine"},
        {Value = 67, Name = "Lapis lazuli"},
        {Value = 68, Name = "Bleu diamant"},
        {Value = 69, Name = "Bleu surfeur"},
        {Value = 70, Name = "Bleu pastel"},
        {Value = 73, Name = "Bleu céleste"},
        {Value = 74, Name = "Bleu rally"},
        {Value = 75, Name = "Bleu cyan"},
        {Value = 77, Name = "Cobalt"},
        {Value = 78, Name = "Bleu électrique"},
        {Value = 79, Name = "Bleu horizon"},
        {Value = 80, Name = "Bleu métallisé"},
        {Value = 82, Name = "Aigue marine"},
        {Value = 83, Name = "Bleu agathe"},
        {Value = 84, Name = "Zirconium"},
        {Value = 85, Name = "Spinelle"},
        {Value = 86, Name = "Tourmaline"},
        {Value = 87, Name = "Bleu paradis"},
        {Value = 127, Name = "Bubble gum"},
        {Value = 140, Name = "Bleu minuit"},
        {Value = 141, Name = "Bleu interdit"},
        {Value = 146, Name = "Bleu glacier"},
    },
    ["Chrome"] = {
        {Value = 117, Name = "Chrome"},
        {Value = 118, Name = "Chrome brossé"},
        {Value = 119, Name = "Chrome noir"},
        {Value = 120, Name = "Aluminium brossé"},
    },
    ["Or"] = {
        {Value = 37, Name = "Or"},
        {Value = 158, Name = "Or pure"},
        {Value = 159, Name = "Or brossé"},
        {Value = 160, Name = "Or clair"},
    },
}