MenuTheme = {
    Default = {
        Banner = {
            R = 13,
            G = 24,
            B = 33,
            A = 255,
        },
        Background = {
            R = 13,
            G = 24,
            B = 33,
            A = 200,
        },
        Selection = {
            R = 123,
            G = 137,
            B = 138,
            A = 127.5,
        },
        Desc = {
            R = 13,
            G = 24,
            B = 33,
            A = 150,
        },
        Txt = {
            R = 191,
            G = 204,
            B = 148,
            A = 255,
        },
    },
    Red = {
        Banner = {
            R = 150,
            G = 25,
            B = 25,
            A = 200,
        },
        Background = {
            R = 150,
            G = 25,
            B = 25,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 150,
            G = 25,
            B = 25,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Green = {
        Banner = {
            R = 25,
            G = 150,
            B = 25,
            A = 200,
        },
        Background = {
            R = 25,
            G = 150,
            B = 25,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 25,
            G = 150,
            B = 25,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Blue = {
        Banner = {
            R = 25,
            G = 25,
            B = 150,
            A = 200,
        },
        Background = {
            R = 25,
            G = 25,
            B = 150,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 25,
            G = 25,
            B = 150,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Orange = {
        Banner = {
            R = 200,
            G = 125,
            B = 1,
            A = 200,
        },
        Background = {
            R = 200,
            G = 125,
            B = 1,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 200,
            G = 125,
            B = 1,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Yellow = {
        Banner = {
            R = 255,
            G = 255,
            B = 1,
            A = 200,
        },
        Background = {
            R = 255,
            G = 255,
            B = 1,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 255,
            G = 255,
            B = 1,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Bgreen = {
        Banner = {
            R = 1,
            G = 200,
            B = 150,
            A = 200,
        },
        Background = {
            R = 1,
            G = 200,
            B = 150,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 1,
            G = 200,
            B = 150,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Purple = {
        Banner = {
            R = 75,
            G = 1,
            B = 200,
            A = 200,
        },
        Background = {
            R = 75,
            G = 1,
            B = 200,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 75,
            G = 1,
            B = 200,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Pink = {
        Banner = {
            R = 200,
            G = 1,
            B = 200,
            A = 200,
        },
        Background = {
            R = 200,
            G = 1,
            B = 200,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 200,
            G = 1,
            B = 200,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
    Brown = {
        Banner = {
            R = 100,
            G = 50,
            B = 1,
            A = 200,
        },
        Background = {
            R = 100,
            G = 50,
            B = 1,
            A = 100,
        },
        Selection = {
            R = 255,
            G = 255,
            B = 255,
            A = 75,
        },
        Desc = {
            R = 100,
            G = 50,
            B = 1,
            A = 125,
        },
        Txt = {
            R = 255,
            G = 255,
            B = 255,
            A = 255,
        },
    },
}