DensityTiming = 2000
DensityMultiplier = 0.5


Citizen.CreateThread(function()
	while true do
        Citizen.Wait(DensityTiming)
	    SetVehicleDensityMultiplierThisFrame(DensityMultiplier)
	    SetPedDensityMultiplierThisFrame(DensityMultiplier)
	    SetRandomVehicleDensityMultiplierThisFrame(DensityMultiplier)
	    SetParkedVehicleDensityMultiplierThisFrame(DensityMultiplier)
	    SetScenarioPedDensityMultiplierThisFrame(DensityMultiplier, DensityMultiplier)
    end
    while true do
        Citizen.Wait(150)
		N_0xf4f2c0d4ee209e20()
        RemoveAllPickupsOfType(0xDF711959)
        RemoveAllPickupsOfType(0xF9AFB48F)
		RemoveAllPickupsOfType(0xA9355DCD)
        DisablePlayerVehicleRewards(PlayerId())
    end
end)

SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_HILLBILLY"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_BALLAS"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_MEXICAN"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_FAMILY"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_MARABUNTE"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_SALVA"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("GANG_1"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("GANG_2"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("GANG_9"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("GANG_10"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("FIREMAN"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("MEDIC"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, GetHashKey("COP"), GetHashKey('PLAYER'))
SetVehicleModelIsSuppressed(GetHashKey("feltzer2"), true) 
SetVehicleModelIsSuppressed(GetHashKey("feltzer3"), true) 
SetVehicleModelIsSuppressed(GetHashKey("jester"), true) 
SetVehicleModelIsSuppressed(GetHashKey("jester2"), true) 
SetVehicleModelIsSuppressed(GetHashKey("jester3"), true) 
SetVehicleModelIsSuppressed(GetHashKey("massacro"), true) 
SetVehicleModelIsSuppressed(GetHashKey("massacro2"), true) 
SetVehicleModelIsSuppressed(GetHashKey("adder"), true) 
SetVehicleModelIsSuppressed(GetHashKey("infernus"), true) 
SetVehicleModelIsSuppressed(GetHashKey("infernus2"), true) 
SetVehicleModelIsSuppressed(GetHashKey("zentorno"), true) 
SetVehicleModelIsSuppressed(GetHashKey("comet2"), true) 
SetVehicleModelIsSuppressed(GetHashKey("comet3"), true) 
SetVehicleModelIsSuppressed(GetHashKey("comet4"), true) 
SetVehicleModelIsSuppressed(GetHashKey("comet5"), true) 
SetVehicleModelIsSuppressed(GetHashKey("turismor"), true)